// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: google/cloud/bigquery/v2/encryption_config.proto

//go:build !protoopaque

package bigquerypb

import (
	reflect "reflect"
	unsafe "unsafe"

	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Configuration for Cloud KMS encryption settings.
type EncryptionConfiguration struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Optional. Describes the Cloud KMS encryption key that will be used to
	// protect destination BigQuery table. The BigQuery Service Account associated
	// with your project requires access to this encryption key.
	KmsKeyName    *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=kms_key_name,json=kmsKeyName,proto3" json:"kms_key_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptionConfiguration) Reset() {
	*x = EncryptionConfiguration{}
	mi := &file_google_cloud_bigquery_v2_encryption_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptionConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptionConfiguration) ProtoMessage() {}

func (x *EncryptionConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_bigquery_v2_encryption_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EncryptionConfiguration) GetKmsKeyName() *wrapperspb.StringValue {
	if x != nil {
		return x.KmsKeyName
	}
	return nil
}

func (x *EncryptionConfiguration) SetKmsKeyName(v *wrapperspb.StringValue) {
	x.KmsKeyName = v
}

func (x *EncryptionConfiguration) HasKmsKeyName() bool {
	if x == nil {
		return false
	}
	return x.KmsKeyName != nil
}

func (x *EncryptionConfiguration) ClearKmsKeyName() {
	x.KmsKeyName = nil
}

type EncryptionConfiguration_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Optional. Describes the Cloud KMS encryption key that will be used to
	// protect destination BigQuery table. The BigQuery Service Account associated
	// with your project requires access to this encryption key.
	KmsKeyName *wrapperspb.StringValue
}

func (b0 EncryptionConfiguration_builder) Build() *EncryptionConfiguration {
	m0 := &EncryptionConfiguration{}
	b, x := &b0, m0
	_, _ = b, x
	x.KmsKeyName = b.KmsKeyName
	return m0
}

var File_google_cloud_bigquery_v2_encryption_config_proto protoreflect.FileDescriptor

const file_google_cloud_bigquery_v2_encryption_config_proto_rawDesc = "" +
	"\n" +
	"0google/cloud/bigquery/v2/encryption_config.proto\x12\x18google.cloud.bigquery.v2\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1egoogle/protobuf/wrappers.proto\"^\n" +
	"\x17EncryptionConfiguration\x12C\n" +
	"\fkms_key_name\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueB\x03\xe0A\x01R\n" +
	"kmsKeyNameBr\n" +
	"\x1ccom.google.cloud.bigquery.v2B\x15EncryptionConfigProtoZ;cloud.google.com/go/bigquery/v2/apiv2/bigquerypb;bigquerypbb\x06proto3"

var file_google_cloud_bigquery_v2_encryption_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_google_cloud_bigquery_v2_encryption_config_proto_goTypes = []any{
	(*EncryptionConfiguration)(nil), // 0: google.cloud.bigquery.v2.EncryptionConfiguration
	(*wrapperspb.StringValue)(nil),  // 1: google.protobuf.StringValue
}
var file_google_cloud_bigquery_v2_encryption_config_proto_depIdxs = []int32{
	1, // 0: google.cloud.bigquery.v2.EncryptionConfiguration.kms_key_name:type_name -> google.protobuf.StringValue
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_google_cloud_bigquery_v2_encryption_config_proto_init() }
func file_google_cloud_bigquery_v2_encryption_config_proto_init() {
	if File_google_cloud_bigquery_v2_encryption_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_cloud_bigquery_v2_encryption_config_proto_rawDesc), len(file_google_cloud_bigquery_v2_encryption_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_cloud_bigquery_v2_encryption_config_proto_goTypes,
		DependencyIndexes: file_google_cloud_bigquery_v2_encryption_config_proto_depIdxs,
		MessageInfos:      file_google_cloud_bigquery_v2_encryption_config_proto_msgTypes,
	}.Build()
	File_google_cloud_bigquery_v2_encryption_config_proto = out.File
	file_google_cloud_bigquery_v2_encryption_config_proto_goTypes = nil
	file_google_cloud_bigquery_v2_encryption_config_proto_depIdxs = nil
}
