// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: google/cloud/bigquery/v2/external_catalog_table_options.proto

//go:build protoopaque

package bigquerypb

import (
	reflect "reflect"
	unsafe "unsafe"

	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Metadata about open source compatible table. The fields contained in
// these options correspond to Hive metastore's table-level properties.
type ExternalCatalogTableOptions struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Parameters        map[string]string      `protobuf:"bytes,1,rep,name=parameters,proto3" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_StorageDescriptor *StorageDescriptor     `protobuf:"bytes,2,opt,name=storage_descriptor,json=storageDescriptor,proto3"`
	xxx_hidden_ConnectionId      string                 `protobuf:"bytes,3,opt,name=connection_id,json=connectionId,proto3"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *ExternalCatalogTableOptions) Reset() {
	*x = ExternalCatalogTableOptions{}
	mi := &file_google_cloud_bigquery_v2_external_catalog_table_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalCatalogTableOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalCatalogTableOptions) ProtoMessage() {}

func (x *ExternalCatalogTableOptions) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_bigquery_v2_external_catalog_table_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ExternalCatalogTableOptions) GetParameters() map[string]string {
	if x != nil {
		return x.xxx_hidden_Parameters
	}
	return nil
}

func (x *ExternalCatalogTableOptions) GetStorageDescriptor() *StorageDescriptor {
	if x != nil {
		return x.xxx_hidden_StorageDescriptor
	}
	return nil
}

func (x *ExternalCatalogTableOptions) GetConnectionId() string {
	if x != nil {
		return x.xxx_hidden_ConnectionId
	}
	return ""
}

func (x *ExternalCatalogTableOptions) SetParameters(v map[string]string) {
	x.xxx_hidden_Parameters = v
}

func (x *ExternalCatalogTableOptions) SetStorageDescriptor(v *StorageDescriptor) {
	x.xxx_hidden_StorageDescriptor = v
}

func (x *ExternalCatalogTableOptions) SetConnectionId(v string) {
	x.xxx_hidden_ConnectionId = v
}

func (x *ExternalCatalogTableOptions) HasStorageDescriptor() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_StorageDescriptor != nil
}

func (x *ExternalCatalogTableOptions) ClearStorageDescriptor() {
	x.xxx_hidden_StorageDescriptor = nil
}

type ExternalCatalogTableOptions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Optional. A map of the key-value pairs defining the parameters and
	// properties of the open source table. Corresponds with Hive metastore table
	// parameters. Maximum size of 4MiB.
	Parameters map[string]string
	// Optional. A storage descriptor containing information about the physical
	// storage of this table.
	StorageDescriptor *StorageDescriptor
	// Optional. A connection ID that specifies the credentials to be used to read
	// external storage, such as Azure Blob, Cloud Storage, or Amazon S3. This
	// connection is needed to read the open source table from BigQuery. The
	// connection_id format must be either
	// `<project_id>.<location_id>.<connection_id>` or
	// `projects/<project_id>/locations/<location_id>/connections/<connection_id>`.
	ConnectionId string
}

func (b0 ExternalCatalogTableOptions_builder) Build() *ExternalCatalogTableOptions {
	m0 := &ExternalCatalogTableOptions{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Parameters = b.Parameters
	x.xxx_hidden_StorageDescriptor = b.StorageDescriptor
	x.xxx_hidden_ConnectionId = b.ConnectionId
	return m0
}

// Contains information about how a table's data is stored and accessed by open
// source query engines.
type StorageDescriptor struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_LocationUri  string                 `protobuf:"bytes,1,opt,name=location_uri,json=locationUri,proto3"`
	xxx_hidden_InputFormat  string                 `protobuf:"bytes,2,opt,name=input_format,json=inputFormat,proto3"`
	xxx_hidden_OutputFormat string                 `protobuf:"bytes,3,opt,name=output_format,json=outputFormat,proto3"`
	xxx_hidden_SerdeInfo    *SerDeInfo             `protobuf:"bytes,4,opt,name=serde_info,json=serdeInfo,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *StorageDescriptor) Reset() {
	*x = StorageDescriptor{}
	mi := &file_google_cloud_bigquery_v2_external_catalog_table_options_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageDescriptor) ProtoMessage() {}

func (x *StorageDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_bigquery_v2_external_catalog_table_options_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StorageDescriptor) GetLocationUri() string {
	if x != nil {
		return x.xxx_hidden_LocationUri
	}
	return ""
}

func (x *StorageDescriptor) GetInputFormat() string {
	if x != nil {
		return x.xxx_hidden_InputFormat
	}
	return ""
}

func (x *StorageDescriptor) GetOutputFormat() string {
	if x != nil {
		return x.xxx_hidden_OutputFormat
	}
	return ""
}

func (x *StorageDescriptor) GetSerdeInfo() *SerDeInfo {
	if x != nil {
		return x.xxx_hidden_SerdeInfo
	}
	return nil
}

func (x *StorageDescriptor) SetLocationUri(v string) {
	x.xxx_hidden_LocationUri = v
}

func (x *StorageDescriptor) SetInputFormat(v string) {
	x.xxx_hidden_InputFormat = v
}

func (x *StorageDescriptor) SetOutputFormat(v string) {
	x.xxx_hidden_OutputFormat = v
}

func (x *StorageDescriptor) SetSerdeInfo(v *SerDeInfo) {
	x.xxx_hidden_SerdeInfo = v
}

func (x *StorageDescriptor) HasSerdeInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_SerdeInfo != nil
}

func (x *StorageDescriptor) ClearSerdeInfo() {
	x.xxx_hidden_SerdeInfo = nil
}

type StorageDescriptor_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Optional. The physical location of the table
	// (e.g. `gs://spark-dataproc-data/pangea-data/case_sensitive/` or
	// `gs://spark-dataproc-data/pangea-data/*`).
	// The maximum length is 2056 bytes.
	LocationUri string
	// Optional. Specifies the fully qualified class name of the InputFormat
	// (e.g. "org.apache.hadoop.hive.ql.io.orc.OrcInputFormat").
	// The maximum length is 128 characters.
	InputFormat string
	// Optional. Specifies the fully qualified class name of the OutputFormat
	// (e.g. "org.apache.hadoop.hive.ql.io.orc.OrcOutputFormat").
	// The maximum length is 128 characters.
	OutputFormat string
	// Optional. Serializer and deserializer information.
	SerdeInfo *SerDeInfo
}

func (b0 StorageDescriptor_builder) Build() *StorageDescriptor {
	m0 := &StorageDescriptor{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_LocationUri = b.LocationUri
	x.xxx_hidden_InputFormat = b.InputFormat
	x.xxx_hidden_OutputFormat = b.OutputFormat
	x.xxx_hidden_SerdeInfo = b.SerdeInfo
	return m0
}

// Serializer and deserializer information.
type SerDeInfo struct {
	state                           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_SerializationLibrary string                 `protobuf:"bytes,2,opt,name=serialization_library,json=serializationLibrary,proto3"`
	xxx_hidden_Parameters           map[string]string      `protobuf:"bytes,3,rep,name=parameters,proto3" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *SerDeInfo) Reset() {
	*x = SerDeInfo{}
	mi := &file_google_cloud_bigquery_v2_external_catalog_table_options_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SerDeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerDeInfo) ProtoMessage() {}

func (x *SerDeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_bigquery_v2_external_catalog_table_options_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SerDeInfo) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *SerDeInfo) GetSerializationLibrary() string {
	if x != nil {
		return x.xxx_hidden_SerializationLibrary
	}
	return ""
}

func (x *SerDeInfo) GetParameters() map[string]string {
	if x != nil {
		return x.xxx_hidden_Parameters
	}
	return nil
}

func (x *SerDeInfo) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *SerDeInfo) SetSerializationLibrary(v string) {
	x.xxx_hidden_SerializationLibrary = v
}

func (x *SerDeInfo) SetParameters(v map[string]string) {
	x.xxx_hidden_Parameters = v
}

type SerDeInfo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Optional. Name of the SerDe.
	// The maximum length is 256 characters.
	Name string
	// Required. Specifies a fully-qualified class name of the serialization
	// library that is responsible for the translation of data between table
	// representation and the underlying low-level input and output format
	// structures. The maximum length is 256 characters.
	SerializationLibrary string
	// Optional. Key-value pairs that define the initialization parameters for the
	// serialization library.
	// Maximum size 10 Kib.
	Parameters map[string]string
}

func (b0 SerDeInfo_builder) Build() *SerDeInfo {
	m0 := &SerDeInfo{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_SerializationLibrary = b.SerializationLibrary
	x.xxx_hidden_Parameters = b.Parameters
	return m0
}

var File_google_cloud_bigquery_v2_external_catalog_table_options_proto protoreflect.FileDescriptor

const file_google_cloud_bigquery_v2_external_catalog_table_options_proto_rawDesc = "" +
	"\n" +
	"=google/cloud/bigquery/v2/external_catalog_table_options.proto\x12\x18google.cloud.bigquery.v2\x1a\x1fgoogle/api/field_behavior.proto\"\xd3\x02\n" +
	"\x1bExternalCatalogTableOptions\x12j\n" +
	"\n" +
	"parameters\x18\x01 \x03(\v2E.google.cloud.bigquery.v2.ExternalCatalogTableOptions.ParametersEntryB\x03\xe0A\x01R\n" +
	"parameters\x12_\n" +
	"\x12storage_descriptor\x18\x02 \x01(\v2+.google.cloud.bigquery.v2.StorageDescriptorB\x03\xe0A\x01R\x11storageDescriptor\x12(\n" +
	"\rconnection_id\x18\x03 \x01(\tB\x03\xe0A\x01R\fconnectionId\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd6\x01\n" +
	"\x11StorageDescriptor\x12&\n" +
	"\flocation_uri\x18\x01 \x01(\tB\x03\xe0A\x01R\vlocationUri\x12&\n" +
	"\finput_format\x18\x02 \x01(\tB\x03\xe0A\x01R\vinputFormat\x12(\n" +
	"\routput_format\x18\x03 \x01(\tB\x03\xe0A\x01R\foutputFormat\x12G\n" +
	"\n" +
	"serde_info\x18\x04 \x01(\v2#.google.cloud.bigquery.v2.SerDeInfoB\x03\xe0A\x01R\tserdeInfo\"\xf7\x01\n" +
	"\tSerDeInfo\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x01R\x04name\x128\n" +
	"\x15serialization_library\x18\x02 \x01(\tB\x03\xe0A\x02R\x14serializationLibrary\x12X\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v23.google.cloud.bigquery.v2.SerDeInfo.ParametersEntryB\x03\xe0A\x01R\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x7f\n" +
	"\x1ccom.google.cloud.bigquery.v2B ExternalCatalogTableOptionsProtoP\x01Z;cloud.google.com/go/bigquery/v2/apiv2/bigquerypb;bigquerypbb\x06proto3"

var file_google_cloud_bigquery_v2_external_catalog_table_options_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_google_cloud_bigquery_v2_external_catalog_table_options_proto_goTypes = []any{
	(*ExternalCatalogTableOptions)(nil), // 0: google.cloud.bigquery.v2.ExternalCatalogTableOptions
	(*StorageDescriptor)(nil),           // 1: google.cloud.bigquery.v2.StorageDescriptor
	(*SerDeInfo)(nil),                   // 2: google.cloud.bigquery.v2.SerDeInfo
	nil,                                 // 3: google.cloud.bigquery.v2.ExternalCatalogTableOptions.ParametersEntry
	nil,                                 // 4: google.cloud.bigquery.v2.SerDeInfo.ParametersEntry
}
var file_google_cloud_bigquery_v2_external_catalog_table_options_proto_depIdxs = []int32{
	3, // 0: google.cloud.bigquery.v2.ExternalCatalogTableOptions.parameters:type_name -> google.cloud.bigquery.v2.ExternalCatalogTableOptions.ParametersEntry
	1, // 1: google.cloud.bigquery.v2.ExternalCatalogTableOptions.storage_descriptor:type_name -> google.cloud.bigquery.v2.StorageDescriptor
	2, // 2: google.cloud.bigquery.v2.StorageDescriptor.serde_info:type_name -> google.cloud.bigquery.v2.SerDeInfo
	4, // 3: google.cloud.bigquery.v2.SerDeInfo.parameters:type_name -> google.cloud.bigquery.v2.SerDeInfo.ParametersEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_google_cloud_bigquery_v2_external_catalog_table_options_proto_init() }
func file_google_cloud_bigquery_v2_external_catalog_table_options_proto_init() {
	if File_google_cloud_bigquery_v2_external_catalog_table_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_cloud_bigquery_v2_external_catalog_table_options_proto_rawDesc), len(file_google_cloud_bigquery_v2_external_catalog_table_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_cloud_bigquery_v2_external_catalog_table_options_proto_goTypes,
		DependencyIndexes: file_google_cloud_bigquery_v2_external_catalog_table_options_proto_depIdxs,
		MessageInfos:      file_google_cloud_bigquery_v2_external_catalog_table_options_proto_msgTypes,
	}.Build()
	File_google_cloud_bigquery_v2_external_catalog_table_options_proto = out.File
	file_google_cloud_bigquery_v2_external_catalog_table_options_proto_goTypes = nil
	file_google_cloud_bigquery_v2_external_catalog_table_options_proto_depIdxs = nil
}
