// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: google/cloud/bigquery/v2/gen_ai_stats.proto

//go:build protoopaque

package bigquerypb

import (
	reflect "reflect"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Provides error statistics for a GenAi function call.
type GenAiFunctionErrorStats struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Errors        []string               `protobuf:"bytes,3,rep,name=errors,proto3"`
	xxx_hidden_NumFailedRows int64                  `protobuf:"varint,5,opt,name=num_failed_rows,json=numFailedRows,proto3"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *GenAiFunctionErrorStats) Reset() {
	*x = GenAiFunctionErrorStats{}
	mi := &file_google_cloud_bigquery_v2_gen_ai_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenAiFunctionErrorStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenAiFunctionErrorStats) ProtoMessage() {}

func (x *GenAiFunctionErrorStats) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_bigquery_v2_gen_ai_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GenAiFunctionErrorStats) GetErrors() []string {
	if x != nil {
		return x.xxx_hidden_Errors
	}
	return nil
}

func (x *GenAiFunctionErrorStats) GetNumFailedRows() int64 {
	if x != nil {
		return x.xxx_hidden_NumFailedRows
	}
	return 0
}

func (x *GenAiFunctionErrorStats) SetErrors(v []string) {
	x.xxx_hidden_Errors = v
}

func (x *GenAiFunctionErrorStats) SetNumFailedRows(v int64) {
	x.xxx_hidden_NumFailedRows = v
}

type GenAiFunctionErrorStats_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// A list of unique errors at function level (up to 5, truncated to 100
	// chars).
	Errors []string
	// Number of failed rows processed by the function
	NumFailedRows int64
}

func (b0 GenAiFunctionErrorStats_builder) Build() *GenAiFunctionErrorStats {
	m0 := &GenAiFunctionErrorStats{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Errors = b.Errors
	x.xxx_hidden_NumFailedRows = b.NumFailedRows
	return m0
}

// Provides cost optimization statistics for a GenAi function call.
type GenAiFunctionCostOptimizationStats struct {
	state                           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_NumCostOptimizedRows int64                  `protobuf:"varint,1,opt,name=num_cost_optimized_rows,json=numCostOptimizedRows,proto3,oneof"`
	xxx_hidden_Message              *string                `protobuf:"bytes,2,opt,name=message,proto3,oneof"`
	XXX_raceDetectHookData          protoimpl.RaceDetectHookData
	XXX_presence                    [1]uint32
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *GenAiFunctionCostOptimizationStats) Reset() {
	*x = GenAiFunctionCostOptimizationStats{}
	mi := &file_google_cloud_bigquery_v2_gen_ai_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenAiFunctionCostOptimizationStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenAiFunctionCostOptimizationStats) ProtoMessage() {}

func (x *GenAiFunctionCostOptimizationStats) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_bigquery_v2_gen_ai_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GenAiFunctionCostOptimizationStats) GetNumCostOptimizedRows() int64 {
	if x != nil {
		return x.xxx_hidden_NumCostOptimizedRows
	}
	return 0
}

func (x *GenAiFunctionCostOptimizationStats) GetMessage() string {
	if x != nil {
		if x.xxx_hidden_Message != nil {
			return *x.xxx_hidden_Message
		}
		return ""
	}
	return ""
}

func (x *GenAiFunctionCostOptimizationStats) SetNumCostOptimizedRows(v int64) {
	x.xxx_hidden_NumCostOptimizedRows = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *GenAiFunctionCostOptimizationStats) SetMessage(v string) {
	x.xxx_hidden_Message = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *GenAiFunctionCostOptimizationStats) HasNumCostOptimizedRows() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GenAiFunctionCostOptimizationStats) HasMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *GenAiFunctionCostOptimizationStats) ClearNumCostOptimizedRows() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_NumCostOptimizedRows = 0
}

func (x *GenAiFunctionCostOptimizationStats) ClearMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Message = nil
}

type GenAiFunctionCostOptimizationStats_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Number of rows inferred via cost optimized workflow.
	NumCostOptimizedRows *int64
	// System generated message to provide insights into cost optimization state.
	Message *string
}

func (b0 GenAiFunctionCostOptimizationStats_builder) Build() *GenAiFunctionCostOptimizationStats {
	m0 := &GenAiFunctionCostOptimizationStats{}
	b, x := &b0, m0
	_, _ = b, x
	if b.NumCostOptimizedRows != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_NumCostOptimizedRows = *b.NumCostOptimizedRows
	}
	if b.Message != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Message = b.Message
	}
	return m0
}

// Provides cache statistics for a GenAi function call.
type GenAiFunctionCacheStats struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_NumCacheHitRows int64                  `protobuf:"varint,1,opt,name=num_cache_hit_rows,json=numCacheHitRows,proto3,oneof"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *GenAiFunctionCacheStats) Reset() {
	*x = GenAiFunctionCacheStats{}
	mi := &file_google_cloud_bigquery_v2_gen_ai_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenAiFunctionCacheStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenAiFunctionCacheStats) ProtoMessage() {}

func (x *GenAiFunctionCacheStats) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_bigquery_v2_gen_ai_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GenAiFunctionCacheStats) GetNumCacheHitRows() int64 {
	if x != nil {
		return x.xxx_hidden_NumCacheHitRows
	}
	return 0
}

func (x *GenAiFunctionCacheStats) SetNumCacheHitRows(v int64) {
	x.xxx_hidden_NumCacheHitRows = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GenAiFunctionCacheStats) HasNumCacheHitRows() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GenAiFunctionCacheStats) ClearNumCacheHitRows() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_NumCacheHitRows = 0
}

type GenAiFunctionCacheStats_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Number of rows served from cache.
	NumCacheHitRows *int64
}

func (b0 GenAiFunctionCacheStats_builder) Build() *GenAiFunctionCacheStats {
	m0 := &GenAiFunctionCacheStats{}
	b, x := &b0, m0
	_, _ = b, x
	if b.NumCacheHitRows != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_NumCacheHitRows = *b.NumCacheHitRows
	}
	return m0
}

// Provides statistics for each Ai function call within a query.
type GenAiFunctionStats struct {
	state                            protoimpl.MessageState              `protogen:"opaque.v1"`
	xxx_hidden_FunctionName          *string                             `protobuf:"bytes,1,opt,name=function_name,json=functionName,proto3,oneof"`
	xxx_hidden_Prompt                *string                             `protobuf:"bytes,2,opt,name=prompt,proto3,oneof"`
	xxx_hidden_NumProcessedRows      int64                               `protobuf:"varint,3,opt,name=num_processed_rows,json=numProcessedRows,proto3,oneof"`
	xxx_hidden_ErrorStats            *GenAiFunctionErrorStats            `protobuf:"bytes,4,opt,name=error_stats,json=errorStats,proto3,oneof"`
	xxx_hidden_CostOptimizationStats *GenAiFunctionCostOptimizationStats `protobuf:"bytes,5,opt,name=cost_optimization_stats,json=costOptimizationStats,proto3,oneof"`
	xxx_hidden_CacheStats            *GenAiFunctionCacheStats            `protobuf:"bytes,6,opt,name=cache_stats,json=cacheStats,proto3,oneof"`
	XXX_raceDetectHookData           protoimpl.RaceDetectHookData
	XXX_presence                     [1]uint32
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *GenAiFunctionStats) Reset() {
	*x = GenAiFunctionStats{}
	mi := &file_google_cloud_bigquery_v2_gen_ai_stats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenAiFunctionStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenAiFunctionStats) ProtoMessage() {}

func (x *GenAiFunctionStats) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_bigquery_v2_gen_ai_stats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GenAiFunctionStats) GetFunctionName() string {
	if x != nil {
		if x.xxx_hidden_FunctionName != nil {
			return *x.xxx_hidden_FunctionName
		}
		return ""
	}
	return ""
}

func (x *GenAiFunctionStats) GetPrompt() string {
	if x != nil {
		if x.xxx_hidden_Prompt != nil {
			return *x.xxx_hidden_Prompt
		}
		return ""
	}
	return ""
}

func (x *GenAiFunctionStats) GetNumProcessedRows() int64 {
	if x != nil {
		return x.xxx_hidden_NumProcessedRows
	}
	return 0
}

func (x *GenAiFunctionStats) GetErrorStats() *GenAiFunctionErrorStats {
	if x != nil {
		return x.xxx_hidden_ErrorStats
	}
	return nil
}

func (x *GenAiFunctionStats) GetCostOptimizationStats() *GenAiFunctionCostOptimizationStats {
	if x != nil {
		return x.xxx_hidden_CostOptimizationStats
	}
	return nil
}

func (x *GenAiFunctionStats) GetCacheStats() *GenAiFunctionCacheStats {
	if x != nil {
		return x.xxx_hidden_CacheStats
	}
	return nil
}

func (x *GenAiFunctionStats) SetFunctionName(v string) {
	x.xxx_hidden_FunctionName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *GenAiFunctionStats) SetPrompt(v string) {
	x.xxx_hidden_Prompt = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *GenAiFunctionStats) SetNumProcessedRows(v int64) {
	x.xxx_hidden_NumProcessedRows = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *GenAiFunctionStats) SetErrorStats(v *GenAiFunctionErrorStats) {
	x.xxx_hidden_ErrorStats = v
}

func (x *GenAiFunctionStats) SetCostOptimizationStats(v *GenAiFunctionCostOptimizationStats) {
	x.xxx_hidden_CostOptimizationStats = v
}

func (x *GenAiFunctionStats) SetCacheStats(v *GenAiFunctionCacheStats) {
	x.xxx_hidden_CacheStats = v
}

func (x *GenAiFunctionStats) HasFunctionName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GenAiFunctionStats) HasPrompt() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *GenAiFunctionStats) HasNumProcessedRows() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *GenAiFunctionStats) HasErrorStats() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ErrorStats != nil
}

func (x *GenAiFunctionStats) HasCostOptimizationStats() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CostOptimizationStats != nil
}

func (x *GenAiFunctionStats) HasCacheStats() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CacheStats != nil
}

func (x *GenAiFunctionStats) ClearFunctionName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_FunctionName = nil
}

func (x *GenAiFunctionStats) ClearPrompt() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Prompt = nil
}

func (x *GenAiFunctionStats) ClearNumProcessedRows() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_NumProcessedRows = 0
}

func (x *GenAiFunctionStats) ClearErrorStats() {
	x.xxx_hidden_ErrorStats = nil
}

func (x *GenAiFunctionStats) ClearCostOptimizationStats() {
	x.xxx_hidden_CostOptimizationStats = nil
}

func (x *GenAiFunctionStats) ClearCacheStats() {
	x.xxx_hidden_CacheStats = nil
}

type GenAiFunctionStats_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Name of the function.
	FunctionName *string
	// User input prompt of the function (truncated to 20 chars).
	Prompt *string
	// Number of rows processed by this GenAi function.
	// This includes all cost_optimized, llm_inferred and failed_rows.
	NumProcessedRows *int64
	// Error stats for the function.
	ErrorStats *GenAiFunctionErrorStats
	// Cost optimization stats if applied on the rows processed by the function.
	CostOptimizationStats *GenAiFunctionCostOptimizationStats
	// Cache stats for the function.
	CacheStats *GenAiFunctionCacheStats
}

func (b0 GenAiFunctionStats_builder) Build() *GenAiFunctionStats {
	m0 := &GenAiFunctionStats{}
	b, x := &b0, m0
	_, _ = b, x
	if b.FunctionName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_FunctionName = b.FunctionName
	}
	if b.Prompt != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_Prompt = b.Prompt
	}
	if b.NumProcessedRows != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_NumProcessedRows = *b.NumProcessedRows
	}
	x.xxx_hidden_ErrorStats = b.ErrorStats
	x.xxx_hidden_CostOptimizationStats = b.CostOptimizationStats
	x.xxx_hidden_CacheStats = b.CacheStats
	return m0
}

// Provides error statistics for the query job across all AI function calls.
type GenAiErrorStats struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Errors []string               `protobuf:"bytes,1,rep,name=errors,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GenAiErrorStats) Reset() {
	*x = GenAiErrorStats{}
	mi := &file_google_cloud_bigquery_v2_gen_ai_stats_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenAiErrorStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenAiErrorStats) ProtoMessage() {}

func (x *GenAiErrorStats) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_bigquery_v2_gen_ai_stats_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GenAiErrorStats) GetErrors() []string {
	if x != nil {
		return x.xxx_hidden_Errors
	}
	return nil
}

func (x *GenAiErrorStats) SetErrors(v []string) {
	x.xxx_hidden_Errors = v
}

type GenAiErrorStats_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// A list of unique errors at query level (up to 5, truncated to 100 chars)
	Errors []string
}

func (b0 GenAiErrorStats_builder) Build() *GenAiErrorStats {
	m0 := &GenAiErrorStats{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Errors = b.Errors
	return m0
}

// GenAi stats for the query job.
type GenAiStats struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ErrorStats    *GenAiErrorStats       `protobuf:"bytes,4,opt,name=error_stats,json=errorStats,proto3,oneof"`
	xxx_hidden_FunctionStats *[]*GenAiFunctionStats `protobuf:"bytes,5,rep,name=function_stats,json=functionStats,proto3"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *GenAiStats) Reset() {
	*x = GenAiStats{}
	mi := &file_google_cloud_bigquery_v2_gen_ai_stats_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenAiStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenAiStats) ProtoMessage() {}

func (x *GenAiStats) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_bigquery_v2_gen_ai_stats_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GenAiStats) GetErrorStats() *GenAiErrorStats {
	if x != nil {
		return x.xxx_hidden_ErrorStats
	}
	return nil
}

func (x *GenAiStats) GetFunctionStats() []*GenAiFunctionStats {
	if x != nil {
		if x.xxx_hidden_FunctionStats != nil {
			return *x.xxx_hidden_FunctionStats
		}
	}
	return nil
}

func (x *GenAiStats) SetErrorStats(v *GenAiErrorStats) {
	x.xxx_hidden_ErrorStats = v
}

func (x *GenAiStats) SetFunctionStats(v []*GenAiFunctionStats) {
	x.xxx_hidden_FunctionStats = &v
}

func (x *GenAiStats) HasErrorStats() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ErrorStats != nil
}

func (x *GenAiStats) ClearErrorStats() {
	x.xxx_hidden_ErrorStats = nil
}

type GenAiStats_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Job level error stats across all GenAi functions
	ErrorStats *GenAiErrorStats
	// Function level stats for GenAI Functions. For more information, see
	// [Generative AI
	// overview](https://docs.cloud.google.com/bigquery/docs/generative-ai-overview).
	FunctionStats []*GenAiFunctionStats
}

func (b0 GenAiStats_builder) Build() *GenAiStats {
	m0 := &GenAiStats{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ErrorStats = b.ErrorStats
	x.xxx_hidden_FunctionStats = &b.FunctionStats
	return m0
}

var File_google_cloud_bigquery_v2_gen_ai_stats_proto protoreflect.FileDescriptor

const file_google_cloud_bigquery_v2_gen_ai_stats_proto_rawDesc = "" +
	"\n" +
	"+google/cloud/bigquery/v2/gen_ai_stats.proto\x12\x18google.cloud.bigquery.v2\"Y\n" +
	"\x17GenAiFunctionErrorStats\x12\x16\n" +
	"\x06errors\x18\x03 \x03(\tR\x06errors\x12&\n" +
	"\x0fnum_failed_rows\x18\x05 \x01(\x03R\rnumFailedRows\"\xa7\x01\n" +
	"\"GenAiFunctionCostOptimizationStats\x12:\n" +
	"\x17num_cost_optimized_rows\x18\x01 \x01(\x03H\x00R\x14numCostOptimizedRows\x88\x01\x01\x12\x1d\n" +
	"\amessage\x18\x02 \x01(\tH\x01R\amessage\x88\x01\x01B\x1a\n" +
	"\x18_num_cost_optimized_rowsB\n" +
	"\n" +
	"\b_message\"b\n" +
	"\x17GenAiFunctionCacheStats\x120\n" +
	"\x12num_cache_hit_rows\x18\x01 \x01(\x03H\x00R\x0fnumCacheHitRows\x88\x01\x01B\x15\n" +
	"\x13_num_cache_hit_rows\"\xab\x04\n" +
	"\x12GenAiFunctionStats\x12(\n" +
	"\rfunction_name\x18\x01 \x01(\tH\x00R\ffunctionName\x88\x01\x01\x12\x1b\n" +
	"\x06prompt\x18\x02 \x01(\tH\x01R\x06prompt\x88\x01\x01\x121\n" +
	"\x12num_processed_rows\x18\x03 \x01(\x03H\x02R\x10numProcessedRows\x88\x01\x01\x12W\n" +
	"\verror_stats\x18\x04 \x01(\v21.google.cloud.bigquery.v2.GenAiFunctionErrorStatsH\x03R\n" +
	"errorStats\x88\x01\x01\x12y\n" +
	"\x17cost_optimization_stats\x18\x05 \x01(\v2<.google.cloud.bigquery.v2.GenAiFunctionCostOptimizationStatsH\x04R\x15costOptimizationStats\x88\x01\x01\x12W\n" +
	"\vcache_stats\x18\x06 \x01(\v21.google.cloud.bigquery.v2.GenAiFunctionCacheStatsH\x05R\n" +
	"cacheStats\x88\x01\x01B\x10\n" +
	"\x0e_function_nameB\t\n" +
	"\a_promptB\x15\n" +
	"\x13_num_processed_rowsB\x0e\n" +
	"\f_error_statsB\x1a\n" +
	"\x18_cost_optimization_statsB\x0e\n" +
	"\f_cache_stats\")\n" +
	"\x0fGenAiErrorStats\x12\x16\n" +
	"\x06errors\x18\x01 \x03(\tR\x06errors\"\xc2\x01\n" +
	"\n" +
	"GenAiStats\x12O\n" +
	"\verror_stats\x18\x04 \x01(\v2).google.cloud.bigquery.v2.GenAiErrorStatsH\x00R\n" +
	"errorStats\x88\x01\x01\x12S\n" +
	"\x0efunction_stats\x18\x05 \x03(\v2,.google.cloud.bigquery.v2.GenAiFunctionStatsR\rfunctionStatsB\x0e\n" +
	"\f_error_statsBn\n" +
	"\x1ccom.google.cloud.bigquery.v2B\x0fGenAiStatsProtoP\x01Z;cloud.google.com/go/bigquery/v2/apiv2/bigquerypb;bigquerypbb\x06proto3"

var file_google_cloud_bigquery_v2_gen_ai_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_google_cloud_bigquery_v2_gen_ai_stats_proto_goTypes = []any{
	(*GenAiFunctionErrorStats)(nil),            // 0: google.cloud.bigquery.v2.GenAiFunctionErrorStats
	(*GenAiFunctionCostOptimizationStats)(nil), // 1: google.cloud.bigquery.v2.GenAiFunctionCostOptimizationStats
	(*GenAiFunctionCacheStats)(nil),            // 2: google.cloud.bigquery.v2.GenAiFunctionCacheStats
	(*GenAiFunctionStats)(nil),                 // 3: google.cloud.bigquery.v2.GenAiFunctionStats
	(*GenAiErrorStats)(nil),                    // 4: google.cloud.bigquery.v2.GenAiErrorStats
	(*GenAiStats)(nil),                         // 5: google.cloud.bigquery.v2.GenAiStats
}
var file_google_cloud_bigquery_v2_gen_ai_stats_proto_depIdxs = []int32{
	0, // 0: google.cloud.bigquery.v2.GenAiFunctionStats.error_stats:type_name -> google.cloud.bigquery.v2.GenAiFunctionErrorStats
	1, // 1: google.cloud.bigquery.v2.GenAiFunctionStats.cost_optimization_stats:type_name -> google.cloud.bigquery.v2.GenAiFunctionCostOptimizationStats
	2, // 2: google.cloud.bigquery.v2.GenAiFunctionStats.cache_stats:type_name -> google.cloud.bigquery.v2.GenAiFunctionCacheStats
	4, // 3: google.cloud.bigquery.v2.GenAiStats.error_stats:type_name -> google.cloud.bigquery.v2.GenAiErrorStats
	3, // 4: google.cloud.bigquery.v2.GenAiStats.function_stats:type_name -> google.cloud.bigquery.v2.GenAiFunctionStats
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_google_cloud_bigquery_v2_gen_ai_stats_proto_init() }
func file_google_cloud_bigquery_v2_gen_ai_stats_proto_init() {
	if File_google_cloud_bigquery_v2_gen_ai_stats_proto != nil {
		return
	}
	file_google_cloud_bigquery_v2_gen_ai_stats_proto_msgTypes[1].OneofWrappers = []any{}
	file_google_cloud_bigquery_v2_gen_ai_stats_proto_msgTypes[2].OneofWrappers = []any{}
	file_google_cloud_bigquery_v2_gen_ai_stats_proto_msgTypes[3].OneofWrappers = []any{}
	file_google_cloud_bigquery_v2_gen_ai_stats_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_cloud_bigquery_v2_gen_ai_stats_proto_rawDesc), len(file_google_cloud_bigquery_v2_gen_ai_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_cloud_bigquery_v2_gen_ai_stats_proto_goTypes,
		DependencyIndexes: file_google_cloud_bigquery_v2_gen_ai_stats_proto_depIdxs,
		MessageInfos:      file_google_cloud_bigquery_v2_gen_ai_stats_proto_msgTypes,
	}.Build()
	File_google_cloud_bigquery_v2_gen_ai_stats_proto = out.File
	file_google_cloud_bigquery_v2_gen_ai_stats_proto_goTypes = nil
	file_google_cloud_bigquery_v2_gen_ai_stats_proto_depIdxs = nil
}
