// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: google/cloud/bigquery/v2/privacy_policy.proto

//go:build !protoopaque

package bigquerypb

import (
	reflect "reflect"
	unsafe "unsafe"

	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum for Join Restrictions policy.
type JoinRestrictionPolicy_JoinCondition int32

const (
	// A join is neither required nor restricted on any column. Default value.
	JoinRestrictionPolicy_JOIN_CONDITION_UNSPECIFIED JoinRestrictionPolicy_JoinCondition = 0
	// A join is required on at least one of the specified columns.
	JoinRestrictionPolicy_JOIN_ANY JoinRestrictionPolicy_JoinCondition = 1
	// A join is required on all specified columns.
	JoinRestrictionPolicy_JOIN_ALL JoinRestrictionPolicy_JoinCondition = 2
	// A join is not required, but if present it is only permitted on
	// 'join_allowed_columns'
	JoinRestrictionPolicy_JOIN_NOT_REQUIRED JoinRestrictionPolicy_JoinCondition = 3
	// Joins are blocked for all queries.
	JoinRestrictionPolicy_JOIN_BLOCKED JoinRestrictionPolicy_JoinCondition = 4
)

// Enum value maps for JoinRestrictionPolicy_JoinCondition.
var (
	JoinRestrictionPolicy_JoinCondition_name = map[int32]string{
		0: "JOIN_CONDITION_UNSPECIFIED",
		1: "JOIN_ANY",
		2: "JOIN_ALL",
		3: "JOIN_NOT_REQUIRED",
		4: "JOIN_BLOCKED",
	}
	JoinRestrictionPolicy_JoinCondition_value = map[string]int32{
		"JOIN_CONDITION_UNSPECIFIED": 0,
		"JOIN_ANY":                   1,
		"JOIN_ALL":                   2,
		"JOIN_NOT_REQUIRED":          3,
		"JOIN_BLOCKED":               4,
	}
)

func (x JoinRestrictionPolicy_JoinCondition) Enum() *JoinRestrictionPolicy_JoinCondition {
	p := new(JoinRestrictionPolicy_JoinCondition)
	*p = x
	return p
}

func (x JoinRestrictionPolicy_JoinCondition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JoinRestrictionPolicy_JoinCondition) Descriptor() protoreflect.EnumDescriptor {
	return file_google_cloud_bigquery_v2_privacy_policy_proto_enumTypes[0].Descriptor()
}

func (JoinRestrictionPolicy_JoinCondition) Type() protoreflect.EnumType {
	return &file_google_cloud_bigquery_v2_privacy_policy_proto_enumTypes[0]
}

func (x JoinRestrictionPolicy_JoinCondition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Represents privacy policy associated with "aggregation threshold" method.
type AggregationThresholdPolicy struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Optional. The threshold for the "aggregation threshold" policy.
	Threshold *int64 `protobuf:"varint,1,opt,name=threshold,proto3,oneof" json:"threshold,omitempty"`
	// Optional. The privacy unit column(s) associated with this policy.
	// For now, only one column per data source object (table, view) is allowed as
	// a privacy unit column.
	// Representing as a repeated field in metadata for extensibility to
	// multiple columns in future.
	// Duplicates and Repeated struct fields are not allowed.
	// For nested fields, use dot notation ("outer.inner")
	PrivacyUnitColumns []string `protobuf:"bytes,2,rep,name=privacy_unit_columns,json=privacyUnitColumns,proto3" json:"privacy_unit_columns,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AggregationThresholdPolicy) Reset() {
	*x = AggregationThresholdPolicy{}
	mi := &file_google_cloud_bigquery_v2_privacy_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregationThresholdPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregationThresholdPolicy) ProtoMessage() {}

func (x *AggregationThresholdPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_bigquery_v2_privacy_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AggregationThresholdPolicy) GetThreshold() int64 {
	if x != nil && x.Threshold != nil {
		return *x.Threshold
	}
	return 0
}

func (x *AggregationThresholdPolicy) GetPrivacyUnitColumns() []string {
	if x != nil {
		return x.PrivacyUnitColumns
	}
	return nil
}

func (x *AggregationThresholdPolicy) SetThreshold(v int64) {
	x.Threshold = &v
}

func (x *AggregationThresholdPolicy) SetPrivacyUnitColumns(v []string) {
	x.PrivacyUnitColumns = v
}

func (x *AggregationThresholdPolicy) HasThreshold() bool {
	if x == nil {
		return false
	}
	return x.Threshold != nil
}

func (x *AggregationThresholdPolicy) ClearThreshold() {
	x.Threshold = nil
}

type AggregationThresholdPolicy_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Optional. The threshold for the "aggregation threshold" policy.
	Threshold *int64
	// Optional. The privacy unit column(s) associated with this policy.
	// For now, only one column per data source object (table, view) is allowed as
	// a privacy unit column.
	// Representing as a repeated field in metadata for extensibility to
	// multiple columns in future.
	// Duplicates and Repeated struct fields are not allowed.
	// For nested fields, use dot notation ("outer.inner")
	PrivacyUnitColumns []string
}

func (b0 AggregationThresholdPolicy_builder) Build() *AggregationThresholdPolicy {
	m0 := &AggregationThresholdPolicy{}
	b, x := &b0, m0
	_, _ = b, x
	x.Threshold = b.Threshold
	x.PrivacyUnitColumns = b.PrivacyUnitColumns
	return m0
}

// Represents privacy policy associated with "differential privacy" method.
type DifferentialPrivacyPolicy struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Optional. The maximum epsilon value that a query can consume. If the
	// subscriber specifies epsilon as a parameter in a SELECT query, it must be
	// less than or equal to this value. The epsilon parameter controls the amount
	// of noise that is added to the groups — a higher epsilon means less noise.
	MaxEpsilonPerQuery *float64 `protobuf:"fixed64,1,opt,name=max_epsilon_per_query,json=maxEpsilonPerQuery,proto3,oneof" json:"max_epsilon_per_query,omitempty"`
	// Optional. The delta value that is used per query. Delta represents the
	// probability that any row will fail to be epsilon differentially private.
	// Indicates the risk associated with exposing aggregate rows in the result of
	// a query.
	DeltaPerQuery *float64 `protobuf:"fixed64,2,opt,name=delta_per_query,json=deltaPerQuery,proto3,oneof" json:"delta_per_query,omitempty"`
	// Optional. The maximum groups contributed value that is used per query.
	// Represents the maximum number of groups to which each protected entity can
	// contribute. Changing this value does not improve or worsen privacy. The
	// best value for accuracy and utility depends on the query and data.
	MaxGroupsContributed *int64 `protobuf:"varint,3,opt,name=max_groups_contributed,json=maxGroupsContributed,proto3,oneof" json:"max_groups_contributed,omitempty"`
	// Optional. The privacy unit column associated with this policy. Differential
	// privacy policies can only have one privacy unit column per data source
	// object (table, view).
	PrivacyUnitColumn *string `protobuf:"bytes,4,opt,name=privacy_unit_column,json=privacyUnitColumn,proto3,oneof" json:"privacy_unit_column,omitempty"`
	// Optional. The total epsilon budget for all queries against the
	// privacy-protected view. Each subscriber query against this view charges the
	// amount of epsilon they request in their query. If there is sufficient
	// budget, then the subscriber query attempts to complete. It might still fail
	// due to other reasons, in which case the charge is refunded. If there is
	// insufficient budget the query is rejected. There might be multiple charge
	// attempts if a single query references multiple views. In this case there
	// must be sufficient budget for all charges or the query is rejected and
	// charges are refunded in best effort. The budget does not have a refresh
	// policy and can only be updated via ALTER VIEW or circumvented by creating a
	// new view that can be queried with a fresh budget.
	EpsilonBudget *float64 `protobuf:"fixed64,5,opt,name=epsilon_budget,json=epsilonBudget,proto3,oneof" json:"epsilon_budget,omitempty"`
	// Optional. The total delta budget for all queries against the
	// privacy-protected view. Each subscriber query against this view charges the
	// amount of delta that is pre-defined by the contributor through the privacy
	// policy delta_per_query field. If there is sufficient budget, then the
	// subscriber query attempts to complete. It might still fail due to other
	// reasons, in which case the charge is refunded. If there is insufficient
	// budget the query is rejected. There might be multiple charge attempts if a
	// single query references multiple views. In this case there must be
	// sufficient budget for all charges or the query is rejected and charges are
	// refunded in best effort. The budget does not have a refresh policy and can
	// only be updated via ALTER VIEW or circumvented by creating a new view that
	// can be queried with a fresh budget.
	DeltaBudget *float64 `protobuf:"fixed64,6,opt,name=delta_budget,json=deltaBudget,proto3,oneof" json:"delta_budget,omitempty"`
	// Output only. The epsilon budget remaining. If budget is exhausted, no more
	// queries are allowed. Note that the budget for queries that are in progress
	// is deducted before the query executes. If the query fails or is cancelled
	// then the budget is refunded. In this case the amount of budget remaining
	// can increase.
	EpsilonBudgetRemaining *float64 `protobuf:"fixed64,7,opt,name=epsilon_budget_remaining,json=epsilonBudgetRemaining,proto3,oneof" json:"epsilon_budget_remaining,omitempty"`
	// Output only. The delta budget remaining. If budget is exhausted, no more
	// queries are allowed. Note that the budget for queries that are in progress
	// is deducted before the query executes. If the query fails or is cancelled
	// then the budget is refunded. In this case the amount of budget remaining
	// can increase.
	DeltaBudgetRemaining *float64 `protobuf:"fixed64,8,opt,name=delta_budget_remaining,json=deltaBudgetRemaining,proto3,oneof" json:"delta_budget_remaining,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DifferentialPrivacyPolicy) Reset() {
	*x = DifferentialPrivacyPolicy{}
	mi := &file_google_cloud_bigquery_v2_privacy_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DifferentialPrivacyPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DifferentialPrivacyPolicy) ProtoMessage() {}

func (x *DifferentialPrivacyPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_bigquery_v2_privacy_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DifferentialPrivacyPolicy) GetMaxEpsilonPerQuery() float64 {
	if x != nil && x.MaxEpsilonPerQuery != nil {
		return *x.MaxEpsilonPerQuery
	}
	return 0
}

func (x *DifferentialPrivacyPolicy) GetDeltaPerQuery() float64 {
	if x != nil && x.DeltaPerQuery != nil {
		return *x.DeltaPerQuery
	}
	return 0
}

func (x *DifferentialPrivacyPolicy) GetMaxGroupsContributed() int64 {
	if x != nil && x.MaxGroupsContributed != nil {
		return *x.MaxGroupsContributed
	}
	return 0
}

func (x *DifferentialPrivacyPolicy) GetPrivacyUnitColumn() string {
	if x != nil && x.PrivacyUnitColumn != nil {
		return *x.PrivacyUnitColumn
	}
	return ""
}

func (x *DifferentialPrivacyPolicy) GetEpsilonBudget() float64 {
	if x != nil && x.EpsilonBudget != nil {
		return *x.EpsilonBudget
	}
	return 0
}

func (x *DifferentialPrivacyPolicy) GetDeltaBudget() float64 {
	if x != nil && x.DeltaBudget != nil {
		return *x.DeltaBudget
	}
	return 0
}

func (x *DifferentialPrivacyPolicy) GetEpsilonBudgetRemaining() float64 {
	if x != nil && x.EpsilonBudgetRemaining != nil {
		return *x.EpsilonBudgetRemaining
	}
	return 0
}

func (x *DifferentialPrivacyPolicy) GetDeltaBudgetRemaining() float64 {
	if x != nil && x.DeltaBudgetRemaining != nil {
		return *x.DeltaBudgetRemaining
	}
	return 0
}

func (x *DifferentialPrivacyPolicy) SetMaxEpsilonPerQuery(v float64) {
	x.MaxEpsilonPerQuery = &v
}

func (x *DifferentialPrivacyPolicy) SetDeltaPerQuery(v float64) {
	x.DeltaPerQuery = &v
}

func (x *DifferentialPrivacyPolicy) SetMaxGroupsContributed(v int64) {
	x.MaxGroupsContributed = &v
}

func (x *DifferentialPrivacyPolicy) SetPrivacyUnitColumn(v string) {
	x.PrivacyUnitColumn = &v
}

func (x *DifferentialPrivacyPolicy) SetEpsilonBudget(v float64) {
	x.EpsilonBudget = &v
}

func (x *DifferentialPrivacyPolicy) SetDeltaBudget(v float64) {
	x.DeltaBudget = &v
}

func (x *DifferentialPrivacyPolicy) SetEpsilonBudgetRemaining(v float64) {
	x.EpsilonBudgetRemaining = &v
}

func (x *DifferentialPrivacyPolicy) SetDeltaBudgetRemaining(v float64) {
	x.DeltaBudgetRemaining = &v
}

func (x *DifferentialPrivacyPolicy) HasMaxEpsilonPerQuery() bool {
	if x == nil {
		return false
	}
	return x.MaxEpsilonPerQuery != nil
}

func (x *DifferentialPrivacyPolicy) HasDeltaPerQuery() bool {
	if x == nil {
		return false
	}
	return x.DeltaPerQuery != nil
}

func (x *DifferentialPrivacyPolicy) HasMaxGroupsContributed() bool {
	if x == nil {
		return false
	}
	return x.MaxGroupsContributed != nil
}

func (x *DifferentialPrivacyPolicy) HasPrivacyUnitColumn() bool {
	if x == nil {
		return false
	}
	return x.PrivacyUnitColumn != nil
}

func (x *DifferentialPrivacyPolicy) HasEpsilonBudget() bool {
	if x == nil {
		return false
	}
	return x.EpsilonBudget != nil
}

func (x *DifferentialPrivacyPolicy) HasDeltaBudget() bool {
	if x == nil {
		return false
	}
	return x.DeltaBudget != nil
}

func (x *DifferentialPrivacyPolicy) HasEpsilonBudgetRemaining() bool {
	if x == nil {
		return false
	}
	return x.EpsilonBudgetRemaining != nil
}

func (x *DifferentialPrivacyPolicy) HasDeltaBudgetRemaining() bool {
	if x == nil {
		return false
	}
	return x.DeltaBudgetRemaining != nil
}

func (x *DifferentialPrivacyPolicy) ClearMaxEpsilonPerQuery() {
	x.MaxEpsilonPerQuery = nil
}

func (x *DifferentialPrivacyPolicy) ClearDeltaPerQuery() {
	x.DeltaPerQuery = nil
}

func (x *DifferentialPrivacyPolicy) ClearMaxGroupsContributed() {
	x.MaxGroupsContributed = nil
}

func (x *DifferentialPrivacyPolicy) ClearPrivacyUnitColumn() {
	x.PrivacyUnitColumn = nil
}

func (x *DifferentialPrivacyPolicy) ClearEpsilonBudget() {
	x.EpsilonBudget = nil
}

func (x *DifferentialPrivacyPolicy) ClearDeltaBudget() {
	x.DeltaBudget = nil
}

func (x *DifferentialPrivacyPolicy) ClearEpsilonBudgetRemaining() {
	x.EpsilonBudgetRemaining = nil
}

func (x *DifferentialPrivacyPolicy) ClearDeltaBudgetRemaining() {
	x.DeltaBudgetRemaining = nil
}

type DifferentialPrivacyPolicy_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Optional. The maximum epsilon value that a query can consume. If the
	// subscriber specifies epsilon as a parameter in a SELECT query, it must be
	// less than or equal to this value. The epsilon parameter controls the amount
	// of noise that is added to the groups — a higher epsilon means less noise.
	MaxEpsilonPerQuery *float64
	// Optional. The delta value that is used per query. Delta represents the
	// probability that any row will fail to be epsilon differentially private.
	// Indicates the risk associated with exposing aggregate rows in the result of
	// a query.
	DeltaPerQuery *float64
	// Optional. The maximum groups contributed value that is used per query.
	// Represents the maximum number of groups to which each protected entity can
	// contribute. Changing this value does not improve or worsen privacy. The
	// best value for accuracy and utility depends on the query and data.
	MaxGroupsContributed *int64
	// Optional. The privacy unit column associated with this policy. Differential
	// privacy policies can only have one privacy unit column per data source
	// object (table, view).
	PrivacyUnitColumn *string
	// Optional. The total epsilon budget for all queries against the
	// privacy-protected view. Each subscriber query against this view charges the
	// amount of epsilon they request in their query. If there is sufficient
	// budget, then the subscriber query attempts to complete. It might still fail
	// due to other reasons, in which case the charge is refunded. If there is
	// insufficient budget the query is rejected. There might be multiple charge
	// attempts if a single query references multiple views. In this case there
	// must be sufficient budget for all charges or the query is rejected and
	// charges are refunded in best effort. The budget does not have a refresh
	// policy and can only be updated via ALTER VIEW or circumvented by creating a
	// new view that can be queried with a fresh budget.
	EpsilonBudget *float64
	// Optional. The total delta budget for all queries against the
	// privacy-protected view. Each subscriber query against this view charges the
	// amount of delta that is pre-defined by the contributor through the privacy
	// policy delta_per_query field. If there is sufficient budget, then the
	// subscriber query attempts to complete. It might still fail due to other
	// reasons, in which case the charge is refunded. If there is insufficient
	// budget the query is rejected. There might be multiple charge attempts if a
	// single query references multiple views. In this case there must be
	// sufficient budget for all charges or the query is rejected and charges are
	// refunded in best effort. The budget does not have a refresh policy and can
	// only be updated via ALTER VIEW or circumvented by creating a new view that
	// can be queried with a fresh budget.
	DeltaBudget *float64
	// Output only. The epsilon budget remaining. If budget is exhausted, no more
	// queries are allowed. Note that the budget for queries that are in progress
	// is deducted before the query executes. If the query fails or is cancelled
	// then the budget is refunded. In this case the amount of budget remaining
	// can increase.
	EpsilonBudgetRemaining *float64
	// Output only. The delta budget remaining. If budget is exhausted, no more
	// queries are allowed. Note that the budget for queries that are in progress
	// is deducted before the query executes. If the query fails or is cancelled
	// then the budget is refunded. In this case the amount of budget remaining
	// can increase.
	DeltaBudgetRemaining *float64
}

func (b0 DifferentialPrivacyPolicy_builder) Build() *DifferentialPrivacyPolicy {
	m0 := &DifferentialPrivacyPolicy{}
	b, x := &b0, m0
	_, _ = b, x
	x.MaxEpsilonPerQuery = b.MaxEpsilonPerQuery
	x.DeltaPerQuery = b.DeltaPerQuery
	x.MaxGroupsContributed = b.MaxGroupsContributed
	x.PrivacyUnitColumn = b.PrivacyUnitColumn
	x.EpsilonBudget = b.EpsilonBudget
	x.DeltaBudget = b.DeltaBudget
	x.EpsilonBudgetRemaining = b.EpsilonBudgetRemaining
	x.DeltaBudgetRemaining = b.DeltaBudgetRemaining
	return m0
}

// Represents privacy policy associated with "join restrictions". Join
// restriction gives data providers the ability to enforce joins on the
// 'join_allowed_columns' when data is queried from a privacy protected view.
type JoinRestrictionPolicy struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Optional. Specifies if a join is required or not on queries for the view.
	// Default is JOIN_CONDITION_UNSPECIFIED.
	JoinCondition *JoinRestrictionPolicy_JoinCondition `protobuf:"varint,1,opt,name=join_condition,json=joinCondition,proto3,enum=google.cloud.bigquery.v2.JoinRestrictionPolicy_JoinCondition,oneof" json:"join_condition,omitempty"`
	// Optional. The only columns that joins are allowed on.
	// This field is must be specified for join_conditions JOIN_ANY and JOIN_ALL
	// and it cannot be set for JOIN_BLOCKED.
	JoinAllowedColumns []string `protobuf:"bytes,2,rep,name=join_allowed_columns,json=joinAllowedColumns,proto3" json:"join_allowed_columns,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *JoinRestrictionPolicy) Reset() {
	*x = JoinRestrictionPolicy{}
	mi := &file_google_cloud_bigquery_v2_privacy_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRestrictionPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRestrictionPolicy) ProtoMessage() {}

func (x *JoinRestrictionPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_bigquery_v2_privacy_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *JoinRestrictionPolicy) GetJoinCondition() JoinRestrictionPolicy_JoinCondition {
	if x != nil && x.JoinCondition != nil {
		return *x.JoinCondition
	}
	return JoinRestrictionPolicy_JOIN_CONDITION_UNSPECIFIED
}

func (x *JoinRestrictionPolicy) GetJoinAllowedColumns() []string {
	if x != nil {
		return x.JoinAllowedColumns
	}
	return nil
}

func (x *JoinRestrictionPolicy) SetJoinCondition(v JoinRestrictionPolicy_JoinCondition) {
	x.JoinCondition = &v
}

func (x *JoinRestrictionPolicy) SetJoinAllowedColumns(v []string) {
	x.JoinAllowedColumns = v
}

func (x *JoinRestrictionPolicy) HasJoinCondition() bool {
	if x == nil {
		return false
	}
	return x.JoinCondition != nil
}

func (x *JoinRestrictionPolicy) ClearJoinCondition() {
	x.JoinCondition = nil
}

type JoinRestrictionPolicy_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Optional. Specifies if a join is required or not on queries for the view.
	// Default is JOIN_CONDITION_UNSPECIFIED.
	JoinCondition *JoinRestrictionPolicy_JoinCondition
	// Optional. The only columns that joins are allowed on.
	// This field is must be specified for join_conditions JOIN_ANY and JOIN_ALL
	// and it cannot be set for JOIN_BLOCKED.
	JoinAllowedColumns []string
}

func (b0 JoinRestrictionPolicy_builder) Build() *JoinRestrictionPolicy {
	m0 := &JoinRestrictionPolicy{}
	b, x := &b0, m0
	_, _ = b, x
	x.JoinCondition = b.JoinCondition
	x.JoinAllowedColumns = b.JoinAllowedColumns
	return m0
}

// Represents privacy policy that contains the privacy requirements specified by
// the data owner. Currently, this is only supported on views.
type PrivacyPolicy struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Privacy policy associated with this requirement specification. Only one of
	// the privacy methods is allowed per data source object.
	//
	// Types that are valid to be assigned to PrivacyPolicy:
	//
	//	*PrivacyPolicy_AggregationThresholdPolicy
	//	*PrivacyPolicy_DifferentialPrivacyPolicy
	PrivacyPolicy isPrivacyPolicy_PrivacyPolicy `protobuf_oneof:"privacy_policy"`
	// Optional. Join restriction policy is outside of the one of policies, since
	// this policy can be set along with other policies. This policy gives data
	// providers the ability to enforce joins on the 'join_allowed_columns' when
	// data is queried from a privacy protected view.
	JoinRestrictionPolicy *JoinRestrictionPolicy `protobuf:"bytes,1,opt,name=join_restriction_policy,json=joinRestrictionPolicy,proto3,oneof" json:"join_restriction_policy,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PrivacyPolicy) Reset() {
	*x = PrivacyPolicy{}
	mi := &file_google_cloud_bigquery_v2_privacy_policy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivacyPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivacyPolicy) ProtoMessage() {}

func (x *PrivacyPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_bigquery_v2_privacy_policy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PrivacyPolicy) GetPrivacyPolicy() isPrivacyPolicy_PrivacyPolicy {
	if x != nil {
		return x.PrivacyPolicy
	}
	return nil
}

func (x *PrivacyPolicy) GetAggregationThresholdPolicy() *AggregationThresholdPolicy {
	if x != nil {
		if x, ok := x.PrivacyPolicy.(*PrivacyPolicy_AggregationThresholdPolicy); ok {
			return x.AggregationThresholdPolicy
		}
	}
	return nil
}

func (x *PrivacyPolicy) GetDifferentialPrivacyPolicy() *DifferentialPrivacyPolicy {
	if x != nil {
		if x, ok := x.PrivacyPolicy.(*PrivacyPolicy_DifferentialPrivacyPolicy); ok {
			return x.DifferentialPrivacyPolicy
		}
	}
	return nil
}

func (x *PrivacyPolicy) GetJoinRestrictionPolicy() *JoinRestrictionPolicy {
	if x != nil {
		return x.JoinRestrictionPolicy
	}
	return nil
}

func (x *PrivacyPolicy) SetAggregationThresholdPolicy(v *AggregationThresholdPolicy) {
	if v == nil {
		x.PrivacyPolicy = nil
		return
	}
	x.PrivacyPolicy = &PrivacyPolicy_AggregationThresholdPolicy{v}
}

func (x *PrivacyPolicy) SetDifferentialPrivacyPolicy(v *DifferentialPrivacyPolicy) {
	if v == nil {
		x.PrivacyPolicy = nil
		return
	}
	x.PrivacyPolicy = &PrivacyPolicy_DifferentialPrivacyPolicy{v}
}

func (x *PrivacyPolicy) SetJoinRestrictionPolicy(v *JoinRestrictionPolicy) {
	x.JoinRestrictionPolicy = v
}

func (x *PrivacyPolicy) HasPrivacyPolicy() bool {
	if x == nil {
		return false
	}
	return x.PrivacyPolicy != nil
}

func (x *PrivacyPolicy) HasAggregationThresholdPolicy() bool {
	if x == nil {
		return false
	}
	_, ok := x.PrivacyPolicy.(*PrivacyPolicy_AggregationThresholdPolicy)
	return ok
}

func (x *PrivacyPolicy) HasDifferentialPrivacyPolicy() bool {
	if x == nil {
		return false
	}
	_, ok := x.PrivacyPolicy.(*PrivacyPolicy_DifferentialPrivacyPolicy)
	return ok
}

func (x *PrivacyPolicy) HasJoinRestrictionPolicy() bool {
	if x == nil {
		return false
	}
	return x.JoinRestrictionPolicy != nil
}

func (x *PrivacyPolicy) ClearPrivacyPolicy() {
	x.PrivacyPolicy = nil
}

func (x *PrivacyPolicy) ClearAggregationThresholdPolicy() {
	if _, ok := x.PrivacyPolicy.(*PrivacyPolicy_AggregationThresholdPolicy); ok {
		x.PrivacyPolicy = nil
	}
}

func (x *PrivacyPolicy) ClearDifferentialPrivacyPolicy() {
	if _, ok := x.PrivacyPolicy.(*PrivacyPolicy_DifferentialPrivacyPolicy); ok {
		x.PrivacyPolicy = nil
	}
}

func (x *PrivacyPolicy) ClearJoinRestrictionPolicy() {
	x.JoinRestrictionPolicy = nil
}

const PrivacyPolicy_PrivacyPolicy_not_set_case case_PrivacyPolicy_PrivacyPolicy = 0
const PrivacyPolicy_AggregationThresholdPolicy_case case_PrivacyPolicy_PrivacyPolicy = 2
const PrivacyPolicy_DifferentialPrivacyPolicy_case case_PrivacyPolicy_PrivacyPolicy = 3

func (x *PrivacyPolicy) WhichPrivacyPolicy() case_PrivacyPolicy_PrivacyPolicy {
	if x == nil {
		return PrivacyPolicy_PrivacyPolicy_not_set_case
	}
	switch x.PrivacyPolicy.(type) {
	case *PrivacyPolicy_AggregationThresholdPolicy:
		return PrivacyPolicy_AggregationThresholdPolicy_case
	case *PrivacyPolicy_DifferentialPrivacyPolicy:
		return PrivacyPolicy_DifferentialPrivacyPolicy_case
	default:
		return PrivacyPolicy_PrivacyPolicy_not_set_case
	}
}

type PrivacyPolicy_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Privacy policy associated with this requirement specification. Only one of
	// the privacy methods is allowed per data source object.

	// Fields of oneof PrivacyPolicy:
	// Optional. Policy used for aggregation thresholds.
	AggregationThresholdPolicy *AggregationThresholdPolicy
	// Optional. Policy used for differential privacy.
	DifferentialPrivacyPolicy *DifferentialPrivacyPolicy
	// -- end of PrivacyPolicy
	// Optional. Join restriction policy is outside of the one of policies, since
	// this policy can be set along with other policies. This policy gives data
	// providers the ability to enforce joins on the 'join_allowed_columns' when
	// data is queried from a privacy protected view.
	JoinRestrictionPolicy *JoinRestrictionPolicy
}

func (b0 PrivacyPolicy_builder) Build() *PrivacyPolicy {
	m0 := &PrivacyPolicy{}
	b, x := &b0, m0
	_, _ = b, x
	if b.AggregationThresholdPolicy != nil {
		x.PrivacyPolicy = &PrivacyPolicy_AggregationThresholdPolicy{b.AggregationThresholdPolicy}
	}
	if b.DifferentialPrivacyPolicy != nil {
		x.PrivacyPolicy = &PrivacyPolicy_DifferentialPrivacyPolicy{b.DifferentialPrivacyPolicy}
	}
	x.JoinRestrictionPolicy = b.JoinRestrictionPolicy
	return m0
}

type case_PrivacyPolicy_PrivacyPolicy protoreflect.FieldNumber

func (x case_PrivacyPolicy_PrivacyPolicy) String() string {
	md := file_google_cloud_bigquery_v2_privacy_policy_proto_msgTypes[3].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isPrivacyPolicy_PrivacyPolicy interface {
	isPrivacyPolicy_PrivacyPolicy()
}

type PrivacyPolicy_AggregationThresholdPolicy struct {
	// Optional. Policy used for aggregation thresholds.
	AggregationThresholdPolicy *AggregationThresholdPolicy `protobuf:"bytes,2,opt,name=aggregation_threshold_policy,json=aggregationThresholdPolicy,proto3,oneof"`
}

type PrivacyPolicy_DifferentialPrivacyPolicy struct {
	// Optional. Policy used for differential privacy.
	DifferentialPrivacyPolicy *DifferentialPrivacyPolicy `protobuf:"bytes,3,opt,name=differential_privacy_policy,json=differentialPrivacyPolicy,proto3,oneof"`
}

func (*PrivacyPolicy_AggregationThresholdPolicy) isPrivacyPolicy_PrivacyPolicy() {}

func (*PrivacyPolicy_DifferentialPrivacyPolicy) isPrivacyPolicy_PrivacyPolicy() {}

var File_google_cloud_bigquery_v2_privacy_policy_proto protoreflect.FileDescriptor

const file_google_cloud_bigquery_v2_privacy_policy_proto_rawDesc = "" +
	"\n" +
	"-google/cloud/bigquery/v2/privacy_policy.proto\x12\x18google.cloud.bigquery.v2\x1a\x1fgoogle/api/field_behavior.proto\"\x89\x01\n" +
	"\x1aAggregationThresholdPolicy\x12&\n" +
	"\tthreshold\x18\x01 \x01(\x03B\x03\xe0A\x01H\x00R\tthreshold\x88\x01\x01\x125\n" +
	"\x14privacy_unit_columns\x18\x02 \x03(\tB\x03\xe0A\x01R\x12privacyUnitColumnsB\f\n" +
	"\n" +
	"_threshold\"\xa3\x05\n" +
	"\x19DifferentialPrivacyPolicy\x12;\n" +
	"\x15max_epsilon_per_query\x18\x01 \x01(\x01B\x03\xe0A\x01H\x00R\x12maxEpsilonPerQuery\x88\x01\x01\x120\n" +
	"\x0fdelta_per_query\x18\x02 \x01(\x01B\x03\xe0A\x01H\x01R\rdeltaPerQuery\x88\x01\x01\x12>\n" +
	"\x16max_groups_contributed\x18\x03 \x01(\x03B\x03\xe0A\x01H\x02R\x14maxGroupsContributed\x88\x01\x01\x128\n" +
	"\x13privacy_unit_column\x18\x04 \x01(\tB\x03\xe0A\x01H\x03R\x11privacyUnitColumn\x88\x01\x01\x12/\n" +
	"\x0eepsilon_budget\x18\x05 \x01(\x01B\x03\xe0A\x01H\x04R\repsilonBudget\x88\x01\x01\x12+\n" +
	"\fdelta_budget\x18\x06 \x01(\x01B\x03\xe0A\x01H\x05R\vdeltaBudget\x88\x01\x01\x12B\n" +
	"\x18epsilon_budget_remaining\x18\a \x01(\x01B\x03\xe0A\x03H\x06R\x16epsilonBudgetRemaining\x88\x01\x01\x12>\n" +
	"\x16delta_budget_remaining\x18\b \x01(\x01B\x03\xe0A\x03H\aR\x14deltaBudgetRemaining\x88\x01\x01B\x18\n" +
	"\x16_max_epsilon_per_queryB\x12\n" +
	"\x10_delta_per_queryB\x19\n" +
	"\x17_max_groups_contributedB\x16\n" +
	"\x14_privacy_unit_columnB\x11\n" +
	"\x0f_epsilon_budgetB\x0f\n" +
	"\r_delta_budgetB\x1b\n" +
	"\x19_epsilon_budget_remainingB\x19\n" +
	"\x17_delta_budget_remaining\"\xc7\x02\n" +
	"\x15JoinRestrictionPolicy\x12n\n" +
	"\x0ejoin_condition\x18\x01 \x01(\x0e2=.google.cloud.bigquery.v2.JoinRestrictionPolicy.JoinConditionB\x03\xe0A\x01H\x00R\rjoinCondition\x88\x01\x01\x125\n" +
	"\x14join_allowed_columns\x18\x02 \x03(\tB\x03\xe0A\x01R\x12joinAllowedColumns\"t\n" +
	"\rJoinCondition\x12\x1e\n" +
	"\x1aJOIN_CONDITION_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bJOIN_ANY\x10\x01\x12\f\n" +
	"\bJOIN_ALL\x10\x02\x12\x15\n" +
	"\x11JOIN_NOT_REQUIRED\x10\x03\x12\x10\n" +
	"\fJOIN_BLOCKED\x10\x04B\x11\n" +
	"\x0f_join_condition\"\xab\x03\n" +
	"\rPrivacyPolicy\x12}\n" +
	"\x1caggregation_threshold_policy\x18\x02 \x01(\v24.google.cloud.bigquery.v2.AggregationThresholdPolicyB\x03\xe0A\x01H\x00R\x1aaggregationThresholdPolicy\x12z\n" +
	"\x1bdifferential_privacy_policy\x18\x03 \x01(\v23.google.cloud.bigquery.v2.DifferentialPrivacyPolicyB\x03\xe0A\x01H\x00R\x19differentialPrivacyPolicy\x12q\n" +
	"\x17join_restriction_policy\x18\x01 \x01(\v2/.google.cloud.bigquery.v2.JoinRestrictionPolicyB\x03\xe0A\x01H\x01R\x15joinRestrictionPolicy\x88\x01\x01B\x10\n" +
	"\x0eprivacy_policyB\x1a\n" +
	"\x18_join_restriction_policyBo\n" +
	"\x1ccom.google.cloud.bigquery.v2B\x12PrivacyPolicyProtoZ;cloud.google.com/go/bigquery/v2/apiv2/bigquerypb;bigquerypbb\x06proto3"

var file_google_cloud_bigquery_v2_privacy_policy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_google_cloud_bigquery_v2_privacy_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_google_cloud_bigquery_v2_privacy_policy_proto_goTypes = []any{
	(JoinRestrictionPolicy_JoinCondition)(0), // 0: google.cloud.bigquery.v2.JoinRestrictionPolicy.JoinCondition
	(*AggregationThresholdPolicy)(nil),       // 1: google.cloud.bigquery.v2.AggregationThresholdPolicy
	(*DifferentialPrivacyPolicy)(nil),        // 2: google.cloud.bigquery.v2.DifferentialPrivacyPolicy
	(*JoinRestrictionPolicy)(nil),            // 3: google.cloud.bigquery.v2.JoinRestrictionPolicy
	(*PrivacyPolicy)(nil),                    // 4: google.cloud.bigquery.v2.PrivacyPolicy
}
var file_google_cloud_bigquery_v2_privacy_policy_proto_depIdxs = []int32{
	0, // 0: google.cloud.bigquery.v2.JoinRestrictionPolicy.join_condition:type_name -> google.cloud.bigquery.v2.JoinRestrictionPolicy.JoinCondition
	1, // 1: google.cloud.bigquery.v2.PrivacyPolicy.aggregation_threshold_policy:type_name -> google.cloud.bigquery.v2.AggregationThresholdPolicy
	2, // 2: google.cloud.bigquery.v2.PrivacyPolicy.differential_privacy_policy:type_name -> google.cloud.bigquery.v2.DifferentialPrivacyPolicy
	3, // 3: google.cloud.bigquery.v2.PrivacyPolicy.join_restriction_policy:type_name -> google.cloud.bigquery.v2.JoinRestrictionPolicy
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_google_cloud_bigquery_v2_privacy_policy_proto_init() }
func file_google_cloud_bigquery_v2_privacy_policy_proto_init() {
	if File_google_cloud_bigquery_v2_privacy_policy_proto != nil {
		return
	}
	file_google_cloud_bigquery_v2_privacy_policy_proto_msgTypes[0].OneofWrappers = []any{}
	file_google_cloud_bigquery_v2_privacy_policy_proto_msgTypes[1].OneofWrappers = []any{}
	file_google_cloud_bigquery_v2_privacy_policy_proto_msgTypes[2].OneofWrappers = []any{}
	file_google_cloud_bigquery_v2_privacy_policy_proto_msgTypes[3].OneofWrappers = []any{
		(*PrivacyPolicy_AggregationThresholdPolicy)(nil),
		(*PrivacyPolicy_DifferentialPrivacyPolicy)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_cloud_bigquery_v2_privacy_policy_proto_rawDesc), len(file_google_cloud_bigquery_v2_privacy_policy_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_cloud_bigquery_v2_privacy_policy_proto_goTypes,
		DependencyIndexes: file_google_cloud_bigquery_v2_privacy_policy_proto_depIdxs,
		EnumInfos:         file_google_cloud_bigquery_v2_privacy_policy_proto_enumTypes,
		MessageInfos:      file_google_cloud_bigquery_v2_privacy_policy_proto_msgTypes,
	}.Build()
	File_google_cloud_bigquery_v2_privacy_policy_proto = out.File
	file_google_cloud_bigquery_v2_privacy_policy_proto_goTypes = nil
	file_google_cloud_bigquery_v2_privacy_policy_proto_depIdxs = nil
}
