// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: google/cloud/bigquery/v2/query_parameter.proto

//go:build protoopaque

package bigquerypb

import (
	reflect "reflect"
	unsafe "unsafe"

	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The type of a struct parameter.
type QueryParameterStructType struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_Type        *QueryParameterType    `protobuf:"bytes,2,opt,name=type,proto3"`
	xxx_hidden_Description string                 `protobuf:"bytes,3,opt,name=description,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *QueryParameterStructType) Reset() {
	*x = QueryParameterStructType{}
	mi := &file_google_cloud_bigquery_v2_query_parameter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParameterStructType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParameterStructType) ProtoMessage() {}

func (x *QueryParameterStructType) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_bigquery_v2_query_parameter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *QueryParameterStructType) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *QueryParameterStructType) GetType() *QueryParameterType {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return nil
}

func (x *QueryParameterStructType) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *QueryParameterStructType) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *QueryParameterStructType) SetType(v *QueryParameterType) {
	x.xxx_hidden_Type = v
}

func (x *QueryParameterStructType) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

func (x *QueryParameterStructType) HasType() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Type != nil
}

func (x *QueryParameterStructType) ClearType() {
	x.xxx_hidden_Type = nil
}

type QueryParameterStructType_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Optional. The name of this field.
	Name string
	// Required. The type of this field.
	Type *QueryParameterType
	// Optional. Human-oriented description of the field.
	Description string
}

func (b0 QueryParameterStructType_builder) Build() *QueryParameterStructType {
	m0 := &QueryParameterStructType{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_Description = b.Description
	return m0
}

// The type of a query parameter.
type QueryParameterType struct {
	state                         protoimpl.MessageState       `protogen:"opaque.v1"`
	xxx_hidden_Type               string                       `protobuf:"bytes,1,opt,name=type,proto3"`
	xxx_hidden_TimestampPrecision int64                        `protobuf:"varint,5,opt,name=timestamp_precision,json=timestampPrecision,proto3,oneof"`
	xxx_hidden_ArrayType          *QueryParameterType          `protobuf:"bytes,2,opt,name=array_type,json=arrayType,proto3"`
	xxx_hidden_StructTypes        *[]*QueryParameterStructType `protobuf:"bytes,3,rep,name=struct_types,json=structTypes,proto3"`
	xxx_hidden_RangeElementType   *QueryParameterType          `protobuf:"bytes,4,opt,name=range_element_type,json=rangeElementType,proto3"`
	XXX_raceDetectHookData        protoimpl.RaceDetectHookData
	XXX_presence                  [1]uint32
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *QueryParameterType) Reset() {
	*x = QueryParameterType{}
	mi := &file_google_cloud_bigquery_v2_query_parameter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParameterType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParameterType) ProtoMessage() {}

func (x *QueryParameterType) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_bigquery_v2_query_parameter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *QueryParameterType) GetType() string {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return ""
}

func (x *QueryParameterType) GetTimestampPrecision() int64 {
	if x != nil {
		return x.xxx_hidden_TimestampPrecision
	}
	return 0
}

func (x *QueryParameterType) GetArrayType() *QueryParameterType {
	if x != nil {
		return x.xxx_hidden_ArrayType
	}
	return nil
}

func (x *QueryParameterType) GetStructTypes() []*QueryParameterStructType {
	if x != nil {
		if x.xxx_hidden_StructTypes != nil {
			return *x.xxx_hidden_StructTypes
		}
	}
	return nil
}

func (x *QueryParameterType) GetRangeElementType() *QueryParameterType {
	if x != nil {
		return x.xxx_hidden_RangeElementType
	}
	return nil
}

func (x *QueryParameterType) SetType(v string) {
	x.xxx_hidden_Type = v
}

func (x *QueryParameterType) SetTimestampPrecision(v int64) {
	x.xxx_hidden_TimestampPrecision = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *QueryParameterType) SetArrayType(v *QueryParameterType) {
	x.xxx_hidden_ArrayType = v
}

func (x *QueryParameterType) SetStructTypes(v []*QueryParameterStructType) {
	x.xxx_hidden_StructTypes = &v
}

func (x *QueryParameterType) SetRangeElementType(v *QueryParameterType) {
	x.xxx_hidden_RangeElementType = v
}

func (x *QueryParameterType) HasTimestampPrecision() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *QueryParameterType) HasArrayType() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ArrayType != nil
}

func (x *QueryParameterType) HasRangeElementType() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_RangeElementType != nil
}

func (x *QueryParameterType) ClearTimestampPrecision() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_TimestampPrecision = 0
}

func (x *QueryParameterType) ClearArrayType() {
	x.xxx_hidden_ArrayType = nil
}

func (x *QueryParameterType) ClearRangeElementType() {
	x.xxx_hidden_RangeElementType = nil
}

type QueryParameterType_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Required. The top level type of this field.
	Type string
	// Optional. Precision (maximum number of total digits in base 10) for seconds
	// of TIMESTAMP type.
	//
	// Possible values include:
	// * 6 (Default, for TIMESTAMP type with microsecond precision)
	// * 12 (For TIMESTAMP type with picosecond precision)
	TimestampPrecision *int64
	// Optional. The type of the array's elements, if this is an array.
	ArrayType *QueryParameterType
	// Optional. The types of the fields of this struct, in order, if this is a
	// struct.
	StructTypes []*QueryParameterStructType
	// Optional. The element type of the range, if this is a range.
	RangeElementType *QueryParameterType
}

func (b0 QueryParameterType_builder) Build() *QueryParameterType {
	m0 := &QueryParameterType{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Type = b.Type
	if b.TimestampPrecision != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_TimestampPrecision = *b.TimestampPrecision
	}
	x.xxx_hidden_ArrayType = b.ArrayType
	x.xxx_hidden_StructTypes = &b.StructTypes
	x.xxx_hidden_RangeElementType = b.RangeElementType
	return m0
}

// Represents the value of a range.
type RangeValue struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Start *QueryParameterValue   `protobuf:"bytes,1,opt,name=start,proto3"`
	xxx_hidden_End   *QueryParameterValue   `protobuf:"bytes,2,opt,name=end,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RangeValue) Reset() {
	*x = RangeValue{}
	mi := &file_google_cloud_bigquery_v2_query_parameter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeValue) ProtoMessage() {}

func (x *RangeValue) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_bigquery_v2_query_parameter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RangeValue) GetStart() *QueryParameterValue {
	if x != nil {
		return x.xxx_hidden_Start
	}
	return nil
}

func (x *RangeValue) GetEnd() *QueryParameterValue {
	if x != nil {
		return x.xxx_hidden_End
	}
	return nil
}

func (x *RangeValue) SetStart(v *QueryParameterValue) {
	x.xxx_hidden_Start = v
}

func (x *RangeValue) SetEnd(v *QueryParameterValue) {
	x.xxx_hidden_End = v
}

func (x *RangeValue) HasStart() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Start != nil
}

func (x *RangeValue) HasEnd() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_End != nil
}

func (x *RangeValue) ClearStart() {
	x.xxx_hidden_Start = nil
}

func (x *RangeValue) ClearEnd() {
	x.xxx_hidden_End = nil
}

type RangeValue_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Optional. The start value of the range. A missing value represents an
	// unbounded start.
	Start *QueryParameterValue
	// Optional. The end value of the range. A missing value represents an
	// unbounded end.
	End *QueryParameterValue
}

func (b0 RangeValue_builder) Build() *RangeValue {
	m0 := &RangeValue{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Start = b.Start
	x.xxx_hidden_End = b.End
	return m0
}

// The value of a query parameter.
type QueryParameterValue struct {
	state                      protoimpl.MessageState          `protogen:"opaque.v1"`
	xxx_hidden_Value           *wrapperspb.StringValue         `protobuf:"bytes,1,opt,name=value,proto3"`
	xxx_hidden_ArrayValues     *[]*QueryParameterValue         `protobuf:"bytes,2,rep,name=array_values,json=arrayValues,proto3"`
	xxx_hidden_StructValues    map[string]*QueryParameterValue `protobuf:"bytes,3,rep,name=struct_values,json=structValues,proto3" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_RangeValue      *RangeValue                     `protobuf:"bytes,6,opt,name=range_value,json=rangeValue,proto3"`
	xxx_hidden_AltStructValues *[]*structpb.Value              `protobuf:"bytes,5,rep,name=alt_struct_values,json=altStructValues,proto3"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *QueryParameterValue) Reset() {
	*x = QueryParameterValue{}
	mi := &file_google_cloud_bigquery_v2_query_parameter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParameterValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParameterValue) ProtoMessage() {}

func (x *QueryParameterValue) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_bigquery_v2_query_parameter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *QueryParameterValue) GetValue() *wrapperspb.StringValue {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return nil
}

func (x *QueryParameterValue) GetArrayValues() []*QueryParameterValue {
	if x != nil {
		if x.xxx_hidden_ArrayValues != nil {
			return *x.xxx_hidden_ArrayValues
		}
	}
	return nil
}

func (x *QueryParameterValue) GetStructValues() map[string]*QueryParameterValue {
	if x != nil {
		return x.xxx_hidden_StructValues
	}
	return nil
}

func (x *QueryParameterValue) GetRangeValue() *RangeValue {
	if x != nil {
		return x.xxx_hidden_RangeValue
	}
	return nil
}

func (x *QueryParameterValue) GetAltStructValues() []*structpb.Value {
	if x != nil {
		if x.xxx_hidden_AltStructValues != nil {
			return *x.xxx_hidden_AltStructValues
		}
	}
	return nil
}

func (x *QueryParameterValue) SetValue(v *wrapperspb.StringValue) {
	x.xxx_hidden_Value = v
}

func (x *QueryParameterValue) SetArrayValues(v []*QueryParameterValue) {
	x.xxx_hidden_ArrayValues = &v
}

func (x *QueryParameterValue) SetStructValues(v map[string]*QueryParameterValue) {
	x.xxx_hidden_StructValues = v
}

func (x *QueryParameterValue) SetRangeValue(v *RangeValue) {
	x.xxx_hidden_RangeValue = v
}

func (x *QueryParameterValue) SetAltStructValues(v []*structpb.Value) {
	x.xxx_hidden_AltStructValues = &v
}

func (x *QueryParameterValue) HasValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Value != nil
}

func (x *QueryParameterValue) HasRangeValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_RangeValue != nil
}

func (x *QueryParameterValue) ClearValue() {
	x.xxx_hidden_Value = nil
}

func (x *QueryParameterValue) ClearRangeValue() {
	x.xxx_hidden_RangeValue = nil
}

type QueryParameterValue_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Optional. The value of this value, if a simple scalar type.
	Value *wrapperspb.StringValue
	// Optional. The array values, if this is an array type.
	ArrayValues []*QueryParameterValue
	// The struct field values.
	StructValues map[string]*QueryParameterValue
	// Optional. The range value, if this is a range type.
	RangeValue *RangeValue
	// This field should not be used.
	AltStructValues []*structpb.Value
}

func (b0 QueryParameterValue_builder) Build() *QueryParameterValue {
	m0 := &QueryParameterValue{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Value = b.Value
	x.xxx_hidden_ArrayValues = &b.ArrayValues
	x.xxx_hidden_StructValues = b.StructValues
	x.xxx_hidden_RangeValue = b.RangeValue
	x.xxx_hidden_AltStructValues = &b.AltStructValues
	return m0
}

// A parameter given to a query.
type QueryParameter struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name           string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_ParameterType  *QueryParameterType    `protobuf:"bytes,2,opt,name=parameter_type,json=parameterType,proto3"`
	xxx_hidden_ParameterValue *QueryParameterValue   `protobuf:"bytes,3,opt,name=parameter_value,json=parameterValue,proto3"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *QueryParameter) Reset() {
	*x = QueryParameter{}
	mi := &file_google_cloud_bigquery_v2_query_parameter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParameter) ProtoMessage() {}

func (x *QueryParameter) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_bigquery_v2_query_parameter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *QueryParameter) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *QueryParameter) GetParameterType() *QueryParameterType {
	if x != nil {
		return x.xxx_hidden_ParameterType
	}
	return nil
}

func (x *QueryParameter) GetParameterValue() *QueryParameterValue {
	if x != nil {
		return x.xxx_hidden_ParameterValue
	}
	return nil
}

func (x *QueryParameter) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *QueryParameter) SetParameterType(v *QueryParameterType) {
	x.xxx_hidden_ParameterType = v
}

func (x *QueryParameter) SetParameterValue(v *QueryParameterValue) {
	x.xxx_hidden_ParameterValue = v
}

func (x *QueryParameter) HasParameterType() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ParameterType != nil
}

func (x *QueryParameter) HasParameterValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ParameterValue != nil
}

func (x *QueryParameter) ClearParameterType() {
	x.xxx_hidden_ParameterType = nil
}

func (x *QueryParameter) ClearParameterValue() {
	x.xxx_hidden_ParameterValue = nil
}

type QueryParameter_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Optional. If unset, this is a positional parameter. Otherwise, should be
	// unique within a query.
	Name string
	// Required. The type of this parameter.
	ParameterType *QueryParameterType
	// Required. The value of this parameter.
	ParameterValue *QueryParameterValue
}

func (b0 QueryParameter_builder) Build() *QueryParameter {
	m0 := &QueryParameter{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_ParameterType = b.ParameterType
	x.xxx_hidden_ParameterValue = b.ParameterValue
	return m0
}

var File_google_cloud_bigquery_v2_query_parameter_proto protoreflect.FileDescriptor

const file_google_cloud_bigquery_v2_query_parameter_proto_rawDesc = "" +
	"\n" +
	".google/cloud/bigquery/v2/query_parameter.proto\x12\x18google.cloud.bigquery.v2\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xa1\x01\n" +
	"\x18QueryParameterStructType\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x01R\x04name\x12E\n" +
	"\x04type\x18\x02 \x01(\v2,.google.cloud.bigquery.v2.QueryParameterTypeB\x03\xe0A\x02R\x04type\x12%\n" +
	"\vdescription\x18\x03 \x01(\tB\x03\xe0A\x01R\vdescription\"\x8f\x03\n" +
	"\x12QueryParameterType\x12\x17\n" +
	"\x04type\x18\x01 \x01(\tB\x03\xe0A\x02R\x04type\x129\n" +
	"\x13timestamp_precision\x18\x05 \x01(\x03B\x03\xe0A\x01H\x00R\x12timestampPrecision\x88\x01\x01\x12P\n" +
	"\n" +
	"array_type\x18\x02 \x01(\v2,.google.cloud.bigquery.v2.QueryParameterTypeB\x03\xe0A\x01R\tarrayType\x12Z\n" +
	"\fstruct_types\x18\x03 \x03(\v22.google.cloud.bigquery.v2.QueryParameterStructTypeB\x03\xe0A\x01R\vstructTypes\x12_\n" +
	"\x12range_element_type\x18\x04 \x01(\v2,.google.cloud.bigquery.v2.QueryParameterTypeB\x03\xe0A\x01R\x10rangeElementTypeB\x16\n" +
	"\x14_timestamp_precision\"\x9c\x01\n" +
	"\n" +
	"RangeValue\x12H\n" +
	"\x05start\x18\x01 \x01(\v2-.google.cloud.bigquery.v2.QueryParameterValueB\x03\xe0A\x01R\x05start\x12D\n" +
	"\x03end\x18\x02 \x01(\v2-.google.cloud.bigquery.v2.QueryParameterValueB\x03\xe0A\x01R\x03end\"\x8b\x04\n" +
	"\x13QueryParameterValue\x127\n" +
	"\x05value\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueB\x03\xe0A\x01R\x05value\x12U\n" +
	"\farray_values\x18\x02 \x03(\v2-.google.cloud.bigquery.v2.QueryParameterValueB\x03\xe0A\x01R\varrayValues\x12d\n" +
	"\rstruct_values\x18\x03 \x03(\v2?.google.cloud.bigquery.v2.QueryParameterValue.StructValuesEntryR\fstructValues\x12J\n" +
	"\vrange_value\x18\x06 \x01(\v2$.google.cloud.bigquery.v2.RangeValueB\x03\xe0A\x01R\n" +
	"rangeValue\x12B\n" +
	"\x11alt_struct_values\x18\x05 \x03(\v2\x16.google.protobuf.ValueR\x0faltStructValues\x1an\n" +
	"\x11StructValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12C\n" +
	"\x05value\x18\x02 \x01(\v2-.google.cloud.bigquery.v2.QueryParameterValueR\x05value:\x028\x01\"\xe0\x01\n" +
	"\x0eQueryParameter\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x01R\x04name\x12X\n" +
	"\x0eparameter_type\x18\x02 \x01(\v2,.google.cloud.bigquery.v2.QueryParameterTypeB\x03\xe0A\x02R\rparameterType\x12[\n" +
	"\x0fparameter_value\x18\x03 \x01(\v2-.google.cloud.bigquery.v2.QueryParameterValueB\x03\xe0A\x02R\x0eparameterValueBp\n" +
	"\x1ccom.google.cloud.bigquery.v2B\x13QueryParameterProtoZ;cloud.google.com/go/bigquery/v2/apiv2/bigquerypb;bigquerypbb\x06proto3"

var file_google_cloud_bigquery_v2_query_parameter_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_google_cloud_bigquery_v2_query_parameter_proto_goTypes = []any{
	(*QueryParameterStructType)(nil), // 0: google.cloud.bigquery.v2.QueryParameterStructType
	(*QueryParameterType)(nil),       // 1: google.cloud.bigquery.v2.QueryParameterType
	(*RangeValue)(nil),               // 2: google.cloud.bigquery.v2.RangeValue
	(*QueryParameterValue)(nil),      // 3: google.cloud.bigquery.v2.QueryParameterValue
	(*QueryParameter)(nil),           // 4: google.cloud.bigquery.v2.QueryParameter
	nil,                              // 5: google.cloud.bigquery.v2.QueryParameterValue.StructValuesEntry
	(*wrapperspb.StringValue)(nil),   // 6: google.protobuf.StringValue
	(*structpb.Value)(nil),           // 7: google.protobuf.Value
}
var file_google_cloud_bigquery_v2_query_parameter_proto_depIdxs = []int32{
	1,  // 0: google.cloud.bigquery.v2.QueryParameterStructType.type:type_name -> google.cloud.bigquery.v2.QueryParameterType
	1,  // 1: google.cloud.bigquery.v2.QueryParameterType.array_type:type_name -> google.cloud.bigquery.v2.QueryParameterType
	0,  // 2: google.cloud.bigquery.v2.QueryParameterType.struct_types:type_name -> google.cloud.bigquery.v2.QueryParameterStructType
	1,  // 3: google.cloud.bigquery.v2.QueryParameterType.range_element_type:type_name -> google.cloud.bigquery.v2.QueryParameterType
	3,  // 4: google.cloud.bigquery.v2.RangeValue.start:type_name -> google.cloud.bigquery.v2.QueryParameterValue
	3,  // 5: google.cloud.bigquery.v2.RangeValue.end:type_name -> google.cloud.bigquery.v2.QueryParameterValue
	6,  // 6: google.cloud.bigquery.v2.QueryParameterValue.value:type_name -> google.protobuf.StringValue
	3,  // 7: google.cloud.bigquery.v2.QueryParameterValue.array_values:type_name -> google.cloud.bigquery.v2.QueryParameterValue
	5,  // 8: google.cloud.bigquery.v2.QueryParameterValue.struct_values:type_name -> google.cloud.bigquery.v2.QueryParameterValue.StructValuesEntry
	2,  // 9: google.cloud.bigquery.v2.QueryParameterValue.range_value:type_name -> google.cloud.bigquery.v2.RangeValue
	7,  // 10: google.cloud.bigquery.v2.QueryParameterValue.alt_struct_values:type_name -> google.protobuf.Value
	1,  // 11: google.cloud.bigquery.v2.QueryParameter.parameter_type:type_name -> google.cloud.bigquery.v2.QueryParameterType
	3,  // 12: google.cloud.bigquery.v2.QueryParameter.parameter_value:type_name -> google.cloud.bigquery.v2.QueryParameterValue
	3,  // 13: google.cloud.bigquery.v2.QueryParameterValue.StructValuesEntry.value:type_name -> google.cloud.bigquery.v2.QueryParameterValue
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_google_cloud_bigquery_v2_query_parameter_proto_init() }
func file_google_cloud_bigquery_v2_query_parameter_proto_init() {
	if File_google_cloud_bigquery_v2_query_parameter_proto != nil {
		return
	}
	file_google_cloud_bigquery_v2_query_parameter_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_cloud_bigquery_v2_query_parameter_proto_rawDesc), len(file_google_cloud_bigquery_v2_query_parameter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_cloud_bigquery_v2_query_parameter_proto_goTypes,
		DependencyIndexes: file_google_cloud_bigquery_v2_query_parameter_proto_depIdxs,
		MessageInfos:      file_google_cloud_bigquery_v2_query_parameter_proto_msgTypes,
	}.Build()
	File_google_cloud_bigquery_v2_query_parameter_proto = out.File
	file_google_cloud_bigquery_v2_query_parameter_proto_goTypes = nil
	file_google_cloud_bigquery_v2_query_parameter_proto_depIdxs = nil
}
