// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: google/cloud/bigquery/v2/range_partitioning.proto

//go:build protoopaque

package bigquerypb

import (
	reflect "reflect"
	unsafe "unsafe"

	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RangePartitioning struct {
	state            protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_Field string                   `protobuf:"bytes,1,opt,name=field,proto3"`
	xxx_hidden_Range *RangePartitioning_Range `protobuf:"bytes,2,opt,name=range,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RangePartitioning) Reset() {
	*x = RangePartitioning{}
	mi := &file_google_cloud_bigquery_v2_range_partitioning_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangePartitioning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangePartitioning) ProtoMessage() {}

func (x *RangePartitioning) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_bigquery_v2_range_partitioning_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RangePartitioning) GetField() string {
	if x != nil {
		return x.xxx_hidden_Field
	}
	return ""
}

func (x *RangePartitioning) GetRange() *RangePartitioning_Range {
	if x != nil {
		return x.xxx_hidden_Range
	}
	return nil
}

func (x *RangePartitioning) SetField(v string) {
	x.xxx_hidden_Field = v
}

func (x *RangePartitioning) SetRange(v *RangePartitioning_Range) {
	x.xxx_hidden_Range = v
}

func (x *RangePartitioning) HasRange() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Range != nil
}

func (x *RangePartitioning) ClearRange() {
	x.xxx_hidden_Range = nil
}

type RangePartitioning_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Required. The name of the column to partition the table on. It must be a
	// top-level, INT64 column whose mode is NULLABLE or REQUIRED.
	Field string
	// Defines the ranges for range partitioning.
	Range *RangePartitioning_Range
}

func (b0 RangePartitioning_builder) Build() *RangePartitioning {
	m0 := &RangePartitioning{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Field = b.Field
	x.xxx_hidden_Range = b.Range
	return m0
}

// Defines the ranges for range partitioning.
type RangePartitioning_Range struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Start    string                 `protobuf:"bytes,1,opt,name=start,proto3"`
	xxx_hidden_End      string                 `protobuf:"bytes,2,opt,name=end,proto3"`
	xxx_hidden_Interval string                 `protobuf:"bytes,3,opt,name=interval,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RangePartitioning_Range) Reset() {
	*x = RangePartitioning_Range{}
	mi := &file_google_cloud_bigquery_v2_range_partitioning_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangePartitioning_Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangePartitioning_Range) ProtoMessage() {}

func (x *RangePartitioning_Range) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_bigquery_v2_range_partitioning_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RangePartitioning_Range) GetStart() string {
	if x != nil {
		return x.xxx_hidden_Start
	}
	return ""
}

func (x *RangePartitioning_Range) GetEnd() string {
	if x != nil {
		return x.xxx_hidden_End
	}
	return ""
}

func (x *RangePartitioning_Range) GetInterval() string {
	if x != nil {
		return x.xxx_hidden_Interval
	}
	return ""
}

func (x *RangePartitioning_Range) SetStart(v string) {
	x.xxx_hidden_Start = v
}

func (x *RangePartitioning_Range) SetEnd(v string) {
	x.xxx_hidden_End = v
}

func (x *RangePartitioning_Range) SetInterval(v string) {
	x.xxx_hidden_Interval = v
}

type RangePartitioning_Range_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Required. The start of range partitioning, inclusive. This field is an
	// INT64 value represented as a string.
	Start string
	// Required. The end of range partitioning, exclusive. This field is an
	// INT64 value represented as a string.
	End string
	// Required. The width of each interval. This field is an INT64 value
	// represented as a string.
	Interval string
}

func (b0 RangePartitioning_Range_builder) Build() *RangePartitioning_Range {
	m0 := &RangePartitioning_Range{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Start = b.Start
	x.xxx_hidden_End = b.End
	x.xxx_hidden_Interval = b.Interval
	return m0
}

var File_google_cloud_bigquery_v2_range_partitioning_proto protoreflect.FileDescriptor

const file_google_cloud_bigquery_v2_range_partitioning_proto_rawDesc = "" +
	"\n" +
	"1google/cloud/bigquery/v2/range_partitioning.proto\x12\x18google.cloud.bigquery.v2\x1a\x1fgoogle/api/field_behavior.proto\"\xd3\x01\n" +
	"\x11RangePartitioning\x12\x19\n" +
	"\x05field\x18\x01 \x01(\tB\x03\xe0A\x02R\x05field\x12G\n" +
	"\x05range\x18\x02 \x01(\v21.google.cloud.bigquery.v2.RangePartitioning.RangeR\x05range\x1aZ\n" +
	"\x05Range\x12\x19\n" +
	"\x05start\x18\x01 \x01(\tB\x03\xe0A\x02R\x05start\x12\x15\n" +
	"\x03end\x18\x02 \x01(\tB\x03\xe0A\x02R\x03end\x12\x1f\n" +
	"\binterval\x18\x03 \x01(\tB\x03\xe0A\x02R\bintervalBs\n" +
	"\x1ccom.google.cloud.bigquery.v2B\x16RangePartitioningProtoZ;cloud.google.com/go/bigquery/v2/apiv2/bigquerypb;bigquerypbb\x06proto3"

var file_google_cloud_bigquery_v2_range_partitioning_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_google_cloud_bigquery_v2_range_partitioning_proto_goTypes = []any{
	(*RangePartitioning)(nil),       // 0: google.cloud.bigquery.v2.RangePartitioning
	(*RangePartitioning_Range)(nil), // 1: google.cloud.bigquery.v2.RangePartitioning.Range
}
var file_google_cloud_bigquery_v2_range_partitioning_proto_depIdxs = []int32{
	1, // 0: google.cloud.bigquery.v2.RangePartitioning.range:type_name -> google.cloud.bigquery.v2.RangePartitioning.Range
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_google_cloud_bigquery_v2_range_partitioning_proto_init() }
func file_google_cloud_bigquery_v2_range_partitioning_proto_init() {
	if File_google_cloud_bigquery_v2_range_partitioning_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_cloud_bigquery_v2_range_partitioning_proto_rawDesc), len(file_google_cloud_bigquery_v2_range_partitioning_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_google_cloud_bigquery_v2_range_partitioning_proto_goTypes,
		DependencyIndexes: file_google_cloud_bigquery_v2_range_partitioning_proto_depIdxs,
		MessageInfos:      file_google_cloud_bigquery_v2_range_partitioning_proto_msgTypes,
	}.Build()
	File_google_cloud_bigquery_v2_range_partitioning_proto = out.File
	file_google_cloud_bigquery_v2_range_partitioning_proto_goTypes = nil
	file_google_cloud_bigquery_v2_range_partitioning_proto_depIdxs = nil
}
