// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: google/cloud/bigquery/v2/row_access_policy.proto

//go:build !protoopaque

package bigquerypb

import (
	reflect "reflect"
	unsafe "unsafe"

	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for the ListRowAccessPolicies method.
type ListRowAccessPoliciesRequest struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Required. Project ID of the row access policies to list.
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// Required. Dataset ID of row access policies to list.
	DatasetId string `protobuf:"bytes,2,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`
	// Required. Table ID of the table to list row access policies.
	TableId string `protobuf:"bytes,3,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	// Page token, returned by a previous call, to request the next page of
	// results.
	PageToken string `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// The maximum number of results to return in a single response page. Leverage
	// the page tokens to iterate through the entire collection.
	PageSize      int32 `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRowAccessPoliciesRequest) Reset() {
	*x = ListRowAccessPoliciesRequest{}
	mi := &file_google_cloud_bigquery_v2_row_access_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRowAccessPoliciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRowAccessPoliciesRequest) ProtoMessage() {}

func (x *ListRowAccessPoliciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_bigquery_v2_row_access_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListRowAccessPoliciesRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ListRowAccessPoliciesRequest) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

func (x *ListRowAccessPoliciesRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *ListRowAccessPoliciesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListRowAccessPoliciesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRowAccessPoliciesRequest) SetProjectId(v string) {
	x.ProjectId = v
}

func (x *ListRowAccessPoliciesRequest) SetDatasetId(v string) {
	x.DatasetId = v
}

func (x *ListRowAccessPoliciesRequest) SetTableId(v string) {
	x.TableId = v
}

func (x *ListRowAccessPoliciesRequest) SetPageToken(v string) {
	x.PageToken = v
}

func (x *ListRowAccessPoliciesRequest) SetPageSize(v int32) {
	x.PageSize = v
}

type ListRowAccessPoliciesRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Required. Project ID of the row access policies to list.
	ProjectId string
	// Required. Dataset ID of row access policies to list.
	DatasetId string
	// Required. Table ID of the table to list row access policies.
	TableId string
	// Page token, returned by a previous call, to request the next page of
	// results.
	PageToken string
	// The maximum number of results to return in a single response page. Leverage
	// the page tokens to iterate through the entire collection.
	PageSize int32
}

func (b0 ListRowAccessPoliciesRequest_builder) Build() *ListRowAccessPoliciesRequest {
	m0 := &ListRowAccessPoliciesRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.ProjectId = b.ProjectId
	x.DatasetId = b.DatasetId
	x.TableId = b.TableId
	x.PageToken = b.PageToken
	x.PageSize = b.PageSize
	return m0
}

// Response message for the ListRowAccessPolicies method.
type ListRowAccessPoliciesResponse struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Row access policies on the requested table.
	RowAccessPolicies []*RowAccessPolicy `protobuf:"bytes,1,rep,name=row_access_policies,json=rowAccessPolicies,proto3" json:"row_access_policies,omitempty"`
	// A token to request the next page of results.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRowAccessPoliciesResponse) Reset() {
	*x = ListRowAccessPoliciesResponse{}
	mi := &file_google_cloud_bigquery_v2_row_access_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRowAccessPoliciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRowAccessPoliciesResponse) ProtoMessage() {}

func (x *ListRowAccessPoliciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_bigquery_v2_row_access_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListRowAccessPoliciesResponse) GetRowAccessPolicies() []*RowAccessPolicy {
	if x != nil {
		return x.RowAccessPolicies
	}
	return nil
}

func (x *ListRowAccessPoliciesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListRowAccessPoliciesResponse) SetRowAccessPolicies(v []*RowAccessPolicy) {
	x.RowAccessPolicies = v
}

func (x *ListRowAccessPoliciesResponse) SetNextPageToken(v string) {
	x.NextPageToken = v
}

type ListRowAccessPoliciesResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Row access policies on the requested table.
	RowAccessPolicies []*RowAccessPolicy
	// A token to request the next page of results.
	NextPageToken string
}

func (b0 ListRowAccessPoliciesResponse_builder) Build() *ListRowAccessPoliciesResponse {
	m0 := &ListRowAccessPoliciesResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.RowAccessPolicies = b.RowAccessPolicies
	x.NextPageToken = b.NextPageToken
	return m0
}

// Request message for the GetRowAccessPolicy method.
type GetRowAccessPolicyRequest struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Required. Project ID of the table to get the row access policy.
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// Required. Dataset ID of the table to get the row access policy.
	DatasetId string `protobuf:"bytes,2,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`
	// Required. Table ID of the table to get the row access policy.
	TableId string `protobuf:"bytes,3,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	// Required. Policy ID of the row access policy.
	PolicyId      string `protobuf:"bytes,4,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRowAccessPolicyRequest) Reset() {
	*x = GetRowAccessPolicyRequest{}
	mi := &file_google_cloud_bigquery_v2_row_access_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRowAccessPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRowAccessPolicyRequest) ProtoMessage() {}

func (x *GetRowAccessPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_bigquery_v2_row_access_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetRowAccessPolicyRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *GetRowAccessPolicyRequest) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

func (x *GetRowAccessPolicyRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *GetRowAccessPolicyRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *GetRowAccessPolicyRequest) SetProjectId(v string) {
	x.ProjectId = v
}

func (x *GetRowAccessPolicyRequest) SetDatasetId(v string) {
	x.DatasetId = v
}

func (x *GetRowAccessPolicyRequest) SetTableId(v string) {
	x.TableId = v
}

func (x *GetRowAccessPolicyRequest) SetPolicyId(v string) {
	x.PolicyId = v
}

type GetRowAccessPolicyRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Required. Project ID of the table to get the row access policy.
	ProjectId string
	// Required. Dataset ID of the table to get the row access policy.
	DatasetId string
	// Required. Table ID of the table to get the row access policy.
	TableId string
	// Required. Policy ID of the row access policy.
	PolicyId string
}

func (b0 GetRowAccessPolicyRequest_builder) Build() *GetRowAccessPolicyRequest {
	m0 := &GetRowAccessPolicyRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.ProjectId = b.ProjectId
	x.DatasetId = b.DatasetId
	x.TableId = b.TableId
	x.PolicyId = b.PolicyId
	return m0
}

// Request message for the CreateRowAccessPolicy method.
type CreateRowAccessPolicyRequest struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Required. Project ID of the table to get the row access policy.
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// Required. Dataset ID of the table to get the row access policy.
	DatasetId string `protobuf:"bytes,2,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`
	// Required. Table ID of the table to get the row access policy.
	TableId string `protobuf:"bytes,3,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	// Required. The row access policy to create.
	RowAccessPolicy *RowAccessPolicy `protobuf:"bytes,4,opt,name=row_access_policy,json=rowAccessPolicy,proto3" json:"row_access_policy,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateRowAccessPolicyRequest) Reset() {
	*x = CreateRowAccessPolicyRequest{}
	mi := &file_google_cloud_bigquery_v2_row_access_policy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRowAccessPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRowAccessPolicyRequest) ProtoMessage() {}

func (x *CreateRowAccessPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_bigquery_v2_row_access_policy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateRowAccessPolicyRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *CreateRowAccessPolicyRequest) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

func (x *CreateRowAccessPolicyRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *CreateRowAccessPolicyRequest) GetRowAccessPolicy() *RowAccessPolicy {
	if x != nil {
		return x.RowAccessPolicy
	}
	return nil
}

func (x *CreateRowAccessPolicyRequest) SetProjectId(v string) {
	x.ProjectId = v
}

func (x *CreateRowAccessPolicyRequest) SetDatasetId(v string) {
	x.DatasetId = v
}

func (x *CreateRowAccessPolicyRequest) SetTableId(v string) {
	x.TableId = v
}

func (x *CreateRowAccessPolicyRequest) SetRowAccessPolicy(v *RowAccessPolicy) {
	x.RowAccessPolicy = v
}

func (x *CreateRowAccessPolicyRequest) HasRowAccessPolicy() bool {
	if x == nil {
		return false
	}
	return x.RowAccessPolicy != nil
}

func (x *CreateRowAccessPolicyRequest) ClearRowAccessPolicy() {
	x.RowAccessPolicy = nil
}

type CreateRowAccessPolicyRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Required. Project ID of the table to get the row access policy.
	ProjectId string
	// Required. Dataset ID of the table to get the row access policy.
	DatasetId string
	// Required. Table ID of the table to get the row access policy.
	TableId string
	// Required. The row access policy to create.
	RowAccessPolicy *RowAccessPolicy
}

func (b0 CreateRowAccessPolicyRequest_builder) Build() *CreateRowAccessPolicyRequest {
	m0 := &CreateRowAccessPolicyRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.ProjectId = b.ProjectId
	x.DatasetId = b.DatasetId
	x.TableId = b.TableId
	x.RowAccessPolicy = b.RowAccessPolicy
	return m0
}

// Request message for the UpdateRowAccessPolicy method.
type UpdateRowAccessPolicyRequest struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Required. Project ID of the table to get the row access policy.
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// Required. Dataset ID of the table to get the row access policy.
	DatasetId string `protobuf:"bytes,2,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`
	// Required. Table ID of the table to get the row access policy.
	TableId string `protobuf:"bytes,3,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	// Required. Policy ID of the row access policy.
	PolicyId string `protobuf:"bytes,4,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	// Required. The row access policy to update.
	RowAccessPolicy *RowAccessPolicy `protobuf:"bytes,5,opt,name=row_access_policy,json=rowAccessPolicy,proto3" json:"row_access_policy,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateRowAccessPolicyRequest) Reset() {
	*x = UpdateRowAccessPolicyRequest{}
	mi := &file_google_cloud_bigquery_v2_row_access_policy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRowAccessPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRowAccessPolicyRequest) ProtoMessage() {}

func (x *UpdateRowAccessPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_bigquery_v2_row_access_policy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateRowAccessPolicyRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *UpdateRowAccessPolicyRequest) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

func (x *UpdateRowAccessPolicyRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *UpdateRowAccessPolicyRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *UpdateRowAccessPolicyRequest) GetRowAccessPolicy() *RowAccessPolicy {
	if x != nil {
		return x.RowAccessPolicy
	}
	return nil
}

func (x *UpdateRowAccessPolicyRequest) SetProjectId(v string) {
	x.ProjectId = v
}

func (x *UpdateRowAccessPolicyRequest) SetDatasetId(v string) {
	x.DatasetId = v
}

func (x *UpdateRowAccessPolicyRequest) SetTableId(v string) {
	x.TableId = v
}

func (x *UpdateRowAccessPolicyRequest) SetPolicyId(v string) {
	x.PolicyId = v
}

func (x *UpdateRowAccessPolicyRequest) SetRowAccessPolicy(v *RowAccessPolicy) {
	x.RowAccessPolicy = v
}

func (x *UpdateRowAccessPolicyRequest) HasRowAccessPolicy() bool {
	if x == nil {
		return false
	}
	return x.RowAccessPolicy != nil
}

func (x *UpdateRowAccessPolicyRequest) ClearRowAccessPolicy() {
	x.RowAccessPolicy = nil
}

type UpdateRowAccessPolicyRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Required. Project ID of the table to get the row access policy.
	ProjectId string
	// Required. Dataset ID of the table to get the row access policy.
	DatasetId string
	// Required. Table ID of the table to get the row access policy.
	TableId string
	// Required. Policy ID of the row access policy.
	PolicyId string
	// Required. The row access policy to update.
	RowAccessPolicy *RowAccessPolicy
}

func (b0 UpdateRowAccessPolicyRequest_builder) Build() *UpdateRowAccessPolicyRequest {
	m0 := &UpdateRowAccessPolicyRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.ProjectId = b.ProjectId
	x.DatasetId = b.DatasetId
	x.TableId = b.TableId
	x.PolicyId = b.PolicyId
	x.RowAccessPolicy = b.RowAccessPolicy
	return m0
}

// Request message for the DeleteRowAccessPolicy method.
type DeleteRowAccessPolicyRequest struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Required. Project ID of the table to delete the row access policy.
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// Required. Dataset ID of the table to delete the row access policy.
	DatasetId string `protobuf:"bytes,2,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`
	// Required. Table ID of the table to delete the row access policy.
	TableId string `protobuf:"bytes,3,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	// Required. Policy ID of the row access policy.
	PolicyId string `protobuf:"bytes,4,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	// If set to true, it deletes the row access policy even if it's the last row
	// access policy on the table and the deletion will widen the access rather
	// narrowing it.
	Force         *bool `protobuf:"varint,5,opt,name=force,proto3,oneof" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRowAccessPolicyRequest) Reset() {
	*x = DeleteRowAccessPolicyRequest{}
	mi := &file_google_cloud_bigquery_v2_row_access_policy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRowAccessPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRowAccessPolicyRequest) ProtoMessage() {}

func (x *DeleteRowAccessPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_bigquery_v2_row_access_policy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteRowAccessPolicyRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *DeleteRowAccessPolicyRequest) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

func (x *DeleteRowAccessPolicyRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *DeleteRowAccessPolicyRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *DeleteRowAccessPolicyRequest) GetForce() bool {
	if x != nil && x.Force != nil {
		return *x.Force
	}
	return false
}

func (x *DeleteRowAccessPolicyRequest) SetProjectId(v string) {
	x.ProjectId = v
}

func (x *DeleteRowAccessPolicyRequest) SetDatasetId(v string) {
	x.DatasetId = v
}

func (x *DeleteRowAccessPolicyRequest) SetTableId(v string) {
	x.TableId = v
}

func (x *DeleteRowAccessPolicyRequest) SetPolicyId(v string) {
	x.PolicyId = v
}

func (x *DeleteRowAccessPolicyRequest) SetForce(v bool) {
	x.Force = &v
}

func (x *DeleteRowAccessPolicyRequest) HasForce() bool {
	if x == nil {
		return false
	}
	return x.Force != nil
}

func (x *DeleteRowAccessPolicyRequest) ClearForce() {
	x.Force = nil
}

type DeleteRowAccessPolicyRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Required. Project ID of the table to delete the row access policy.
	ProjectId string
	// Required. Dataset ID of the table to delete the row access policy.
	DatasetId string
	// Required. Table ID of the table to delete the row access policy.
	TableId string
	// Required. Policy ID of the row access policy.
	PolicyId string
	// If set to true, it deletes the row access policy even if it's the last row
	// access policy on the table and the deletion will widen the access rather
	// narrowing it.
	Force *bool
}

func (b0 DeleteRowAccessPolicyRequest_builder) Build() *DeleteRowAccessPolicyRequest {
	m0 := &DeleteRowAccessPolicyRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.ProjectId = b.ProjectId
	x.DatasetId = b.DatasetId
	x.TableId = b.TableId
	x.PolicyId = b.PolicyId
	x.Force = b.Force
	return m0
}

// Request message for the BatchDeleteRowAccessPoliciesRequest method.
type BatchDeleteRowAccessPoliciesRequest struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Required. Project ID of the table to delete the row access policies.
	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// Required. Dataset ID of the table to delete the row access policies.
	DatasetId string `protobuf:"bytes,2,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`
	// Required. Table ID of the table to delete the row access policies.
	TableId string `protobuf:"bytes,3,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	// Required. Policy IDs of the row access policies.
	PolicyIds []string `protobuf:"bytes,4,rep,name=policy_ids,json=policyIds,proto3" json:"policy_ids,omitempty"`
	// If set to true, it deletes the row access policy even if it's the last row
	// access policy on the table and the deletion will widen the access rather
	// narrowing it.
	Force         *bool `protobuf:"varint,5,opt,name=force,proto3,oneof" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDeleteRowAccessPoliciesRequest) Reset() {
	*x = BatchDeleteRowAccessPoliciesRequest{}
	mi := &file_google_cloud_bigquery_v2_row_access_policy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDeleteRowAccessPoliciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDeleteRowAccessPoliciesRequest) ProtoMessage() {}

func (x *BatchDeleteRowAccessPoliciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_bigquery_v2_row_access_policy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BatchDeleteRowAccessPoliciesRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *BatchDeleteRowAccessPoliciesRequest) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

func (x *BatchDeleteRowAccessPoliciesRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

func (x *BatchDeleteRowAccessPoliciesRequest) GetPolicyIds() []string {
	if x != nil {
		return x.PolicyIds
	}
	return nil
}

func (x *BatchDeleteRowAccessPoliciesRequest) GetForce() bool {
	if x != nil && x.Force != nil {
		return *x.Force
	}
	return false
}

func (x *BatchDeleteRowAccessPoliciesRequest) SetProjectId(v string) {
	x.ProjectId = v
}

func (x *BatchDeleteRowAccessPoliciesRequest) SetDatasetId(v string) {
	x.DatasetId = v
}

func (x *BatchDeleteRowAccessPoliciesRequest) SetTableId(v string) {
	x.TableId = v
}

func (x *BatchDeleteRowAccessPoliciesRequest) SetPolicyIds(v []string) {
	x.PolicyIds = v
}

func (x *BatchDeleteRowAccessPoliciesRequest) SetForce(v bool) {
	x.Force = &v
}

func (x *BatchDeleteRowAccessPoliciesRequest) HasForce() bool {
	if x == nil {
		return false
	}
	return x.Force != nil
}

func (x *BatchDeleteRowAccessPoliciesRequest) ClearForce() {
	x.Force = nil
}

type BatchDeleteRowAccessPoliciesRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Required. Project ID of the table to delete the row access policies.
	ProjectId string
	// Required. Dataset ID of the table to delete the row access policies.
	DatasetId string
	// Required. Table ID of the table to delete the row access policies.
	TableId string
	// Required. Policy IDs of the row access policies.
	PolicyIds []string
	// If set to true, it deletes the row access policy even if it's the last row
	// access policy on the table and the deletion will widen the access rather
	// narrowing it.
	Force *bool
}

func (b0 BatchDeleteRowAccessPoliciesRequest_builder) Build() *BatchDeleteRowAccessPoliciesRequest {
	m0 := &BatchDeleteRowAccessPoliciesRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.ProjectId = b.ProjectId
	x.DatasetId = b.DatasetId
	x.TableId = b.TableId
	x.PolicyIds = b.PolicyIds
	x.Force = b.Force
	return m0
}

// Represents access on a subset of rows on the specified table, defined by its
// filter predicate. Access to the subset of rows is controlled by its IAM
// policy.
type RowAccessPolicy struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Output only. A hash of this resource.
	Etag string `protobuf:"bytes,1,opt,name=etag,proto3" json:"etag,omitempty"`
	// Required. Reference describing the ID of this row access policy.
	RowAccessPolicyReference *RowAccessPolicyReference `protobuf:"bytes,2,opt,name=row_access_policy_reference,json=rowAccessPolicyReference,proto3" json:"row_access_policy_reference,omitempty"`
	// Required. A SQL boolean expression that represents the rows defined by this
	// row access policy, similar to the boolean expression in a WHERE clause of a
	// SELECT query on a table.
	// References to other tables, routines, and temporary functions are not
	// supported.
	//
	// Examples: region="EU"
	//
	//	date_field = CAST('2019-9-27' as DATE)
	//	nullable_field is not NULL
	//	numeric_field BETWEEN 1.0 AND 5.0
	FilterPredicate string `protobuf:"bytes,3,opt,name=filter_predicate,json=filterPredicate,proto3" json:"filter_predicate,omitempty"`
	// Output only. The time when this row access policy was created, in
	// milliseconds since the epoch.
	CreationTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=creation_time,json=creationTime,proto3" json:"creation_time,omitempty"`
	// Output only. The time when this row access policy was last modified, in
	// milliseconds since the epoch.
	LastModifiedTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_modified_time,json=lastModifiedTime,proto3" json:"last_modified_time,omitempty"`
	// Optional. Input only. The optional list of iam_member users or groups that
	// specifies the initial members that the row-level access policy should be
	// created with.
	//
	// grantees types:
	//
	// - "user:alice@example.com": An email address that represents a specific
	// Google account.
	// - "serviceAccount:my-other-app@appspot.gserviceaccount.com": An email
	// address that represents a service account.
	// - "group:admins@example.com": An email address that represents a Google
	// group.
	// - "domain:example.com":The Google Workspace domain (primary) that
	// represents all the users of that domain.
	// - "allAuthenticatedUsers": A special identifier that represents all service
	// accounts and all users on the internet who have authenticated with a Google
	// Account. This identifier includes accounts that aren't connected to a
	// Google Workspace or Cloud Identity domain, such as personal Gmail accounts.
	// Users who aren't authenticated, such as anonymous visitors, aren't
	// included.
	// - "allUsers":A special identifier that represents anyone who is on
	// the internet, including authenticated and unauthenticated users. Because
	// BigQuery requires authentication before a user can access the service,
	// allUsers includes only authenticated users.
	Grantees      []string `protobuf:"bytes,6,rep,name=grantees,proto3" json:"grantees,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RowAccessPolicy) Reset() {
	*x = RowAccessPolicy{}
	mi := &file_google_cloud_bigquery_v2_row_access_policy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RowAccessPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RowAccessPolicy) ProtoMessage() {}

func (x *RowAccessPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_google_cloud_bigquery_v2_row_access_policy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RowAccessPolicy) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *RowAccessPolicy) GetRowAccessPolicyReference() *RowAccessPolicyReference {
	if x != nil {
		return x.RowAccessPolicyReference
	}
	return nil
}

func (x *RowAccessPolicy) GetFilterPredicate() string {
	if x != nil {
		return x.FilterPredicate
	}
	return ""
}

func (x *RowAccessPolicy) GetCreationTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationTime
	}
	return nil
}

func (x *RowAccessPolicy) GetLastModifiedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastModifiedTime
	}
	return nil
}

func (x *RowAccessPolicy) GetGrantees() []string {
	if x != nil {
		return x.Grantees
	}
	return nil
}

func (x *RowAccessPolicy) SetEtag(v string) {
	x.Etag = v
}

func (x *RowAccessPolicy) SetRowAccessPolicyReference(v *RowAccessPolicyReference) {
	x.RowAccessPolicyReference = v
}

func (x *RowAccessPolicy) SetFilterPredicate(v string) {
	x.FilterPredicate = v
}

func (x *RowAccessPolicy) SetCreationTime(v *timestamppb.Timestamp) {
	x.CreationTime = v
}

func (x *RowAccessPolicy) SetLastModifiedTime(v *timestamppb.Timestamp) {
	x.LastModifiedTime = v
}

func (x *RowAccessPolicy) SetGrantees(v []string) {
	x.Grantees = v
}

func (x *RowAccessPolicy) HasRowAccessPolicyReference() bool {
	if x == nil {
		return false
	}
	return x.RowAccessPolicyReference != nil
}

func (x *RowAccessPolicy) HasCreationTime() bool {
	if x == nil {
		return false
	}
	return x.CreationTime != nil
}

func (x *RowAccessPolicy) HasLastModifiedTime() bool {
	if x == nil {
		return false
	}
	return x.LastModifiedTime != nil
}

func (x *RowAccessPolicy) ClearRowAccessPolicyReference() {
	x.RowAccessPolicyReference = nil
}

func (x *RowAccessPolicy) ClearCreationTime() {
	x.CreationTime = nil
}

func (x *RowAccessPolicy) ClearLastModifiedTime() {
	x.LastModifiedTime = nil
}

type RowAccessPolicy_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Output only. A hash of this resource.
	Etag string
	// Required. Reference describing the ID of this row access policy.
	RowAccessPolicyReference *RowAccessPolicyReference
	// Required. A SQL boolean expression that represents the rows defined by this
	// row access policy, similar to the boolean expression in a WHERE clause of a
	// SELECT query on a table.
	// References to other tables, routines, and temporary functions are not
	// supported.
	//
	// Examples: region="EU"
	//
	//	date_field = CAST('2019-9-27' as DATE)
	//	nullable_field is not NULL
	//	numeric_field BETWEEN 1.0 AND 5.0
	FilterPredicate string
	// Output only. The time when this row access policy was created, in
	// milliseconds since the epoch.
	CreationTime *timestamppb.Timestamp
	// Output only. The time when this row access policy was last modified, in
	// milliseconds since the epoch.
	LastModifiedTime *timestamppb.Timestamp
	// Optional. Input only. The optional list of iam_member users or groups that
	// specifies the initial members that the row-level access policy should be
	// created with.
	//
	// grantees types:
	//
	// - "user:alice@example.com": An email address that represents a specific
	// Google account.
	// - "serviceAccount:my-other-app@appspot.gserviceaccount.com": An email
	// address that represents a service account.
	// - "group:admins@example.com": An email address that represents a Google
	// group.
	// - "domain:example.com":The Google Workspace domain (primary) that
	// represents all the users of that domain.
	// - "allAuthenticatedUsers": A special identifier that represents all service
	// accounts and all users on the internet who have authenticated with a Google
	// Account. This identifier includes accounts that aren't connected to a
	// Google Workspace or Cloud Identity domain, such as personal Gmail accounts.
	// Users who aren't authenticated, such as anonymous visitors, aren't
	// included.
	// - "allUsers":A special identifier that represents anyone who is on
	// the internet, including authenticated and unauthenticated users. Because
	// BigQuery requires authentication before a user can access the service,
	// allUsers includes only authenticated users.
	Grantees []string
}

func (b0 RowAccessPolicy_builder) Build() *RowAccessPolicy {
	m0 := &RowAccessPolicy{}
	b, x := &b0, m0
	_, _ = b, x
	x.Etag = b.Etag
	x.RowAccessPolicyReference = b.RowAccessPolicyReference
	x.FilterPredicate = b.FilterPredicate
	x.CreationTime = b.CreationTime
	x.LastModifiedTime = b.LastModifiedTime
	x.Grantees = b.Grantees
	return m0
}

var File_google_cloud_bigquery_v2_row_access_policy_proto protoreflect.FileDescriptor

const file_google_cloud_bigquery_v2_row_access_policy_proto_rawDesc = "" +
	"\n" +
	"0google/cloud/bigquery/v2/row_access_policy.proto\x12\x18google.cloud.bigquery.v2\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a:google/cloud/bigquery/v2/row_access_policy_reference.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc2\x01\n" +
	"\x1cListRowAccessPoliciesRequest\x12\"\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tprojectId\x12\"\n" +
	"\n" +
	"dataset_id\x18\x02 \x01(\tB\x03\xe0A\x02R\tdatasetId\x12\x1e\n" +
	"\btable_id\x18\x03 \x01(\tB\x03\xe0A\x02R\atableId\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"\xa2\x01\n" +
	"\x1dListRowAccessPoliciesResponse\x12Y\n" +
	"\x13row_access_policies\x18\x01 \x03(\v2).google.cloud.bigquery.v2.RowAccessPolicyR\x11rowAccessPolicies\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xa5\x01\n" +
	"\x19GetRowAccessPolicyRequest\x12\"\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tprojectId\x12\"\n" +
	"\n" +
	"dataset_id\x18\x02 \x01(\tB\x03\xe0A\x02R\tdatasetId\x12\x1e\n" +
	"\btable_id\x18\x03 \x01(\tB\x03\xe0A\x02R\atableId\x12 \n" +
	"\tpolicy_id\x18\x04 \x01(\tB\x03\xe0A\x02R\bpolicyId\"\xe2\x01\n" +
	"\x1cCreateRowAccessPolicyRequest\x12\"\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tprojectId\x12\"\n" +
	"\n" +
	"dataset_id\x18\x02 \x01(\tB\x03\xe0A\x02R\tdatasetId\x12\x1e\n" +
	"\btable_id\x18\x03 \x01(\tB\x03\xe0A\x02R\atableId\x12Z\n" +
	"\x11row_access_policy\x18\x04 \x01(\v2).google.cloud.bigquery.v2.RowAccessPolicyB\x03\xe0A\x02R\x0frowAccessPolicy\"\x84\x02\n" +
	"\x1cUpdateRowAccessPolicyRequest\x12\"\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tprojectId\x12\"\n" +
	"\n" +
	"dataset_id\x18\x02 \x01(\tB\x03\xe0A\x02R\tdatasetId\x12\x1e\n" +
	"\btable_id\x18\x03 \x01(\tB\x03\xe0A\x02R\atableId\x12 \n" +
	"\tpolicy_id\x18\x04 \x01(\tB\x03\xe0A\x02R\bpolicyId\x12Z\n" +
	"\x11row_access_policy\x18\x05 \x01(\v2).google.cloud.bigquery.v2.RowAccessPolicyB\x03\xe0A\x02R\x0frowAccessPolicy\"\xcd\x01\n" +
	"\x1cDeleteRowAccessPolicyRequest\x12\"\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tprojectId\x12\"\n" +
	"\n" +
	"dataset_id\x18\x02 \x01(\tB\x03\xe0A\x02R\tdatasetId\x12\x1e\n" +
	"\btable_id\x18\x03 \x01(\tB\x03\xe0A\x02R\atableId\x12 \n" +
	"\tpolicy_id\x18\x04 \x01(\tB\x03\xe0A\x02R\bpolicyId\x12\x19\n" +
	"\x05force\x18\x05 \x01(\bH\x00R\x05force\x88\x01\x01B\b\n" +
	"\x06_force\"\xd6\x01\n" +
	"#BatchDeleteRowAccessPoliciesRequest\x12\"\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tprojectId\x12\"\n" +
	"\n" +
	"dataset_id\x18\x02 \x01(\tB\x03\xe0A\x02R\tdatasetId\x12\x1e\n" +
	"\btable_id\x18\x03 \x01(\tB\x03\xe0A\x02R\atableId\x12\"\n" +
	"\n" +
	"policy_ids\x18\x04 \x03(\tB\x03\xe0A\x02R\tpolicyIds\x12\x19\n" +
	"\x05force\x18\x05 \x01(\bH\x00R\x05force\x88\x01\x01B\b\n" +
	"\x06_force\"\x8b\x03\n" +
	"\x0fRowAccessPolicy\x12\x17\n" +
	"\x04etag\x18\x01 \x01(\tB\x03\xe0A\x03R\x04etag\x12v\n" +
	"\x1brow_access_policy_reference\x18\x02 \x01(\v22.google.cloud.bigquery.v2.RowAccessPolicyReferenceB\x03\xe0A\x02R\x18rowAccessPolicyReference\x12.\n" +
	"\x10filter_predicate\x18\x03 \x01(\tB\x03\xe0A\x02R\x0ffilterPredicate\x12D\n" +
	"\rcreation_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\fcreationTime\x12M\n" +
	"\x12last_modified_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\x10lastModifiedTime\x12\"\n" +
	"\bgrantees\x18\x06 \x03(\tB\x06\xe0A\x04\xe0A\x01R\bgrantees2\x90\r\n" +
	"\x16RowAccessPolicyService\x12\xf4\x01\n" +
	"\x15ListRowAccessPolicies\x126.google.cloud.bigquery.v2.ListRowAccessPoliciesRequest\x1a7.google.cloud.bigquery.v2.ListRowAccessPoliciesResponse\"j\x82\xd3\xe4\x93\x02d\x12b/bigquery/v2/projects/{project_id=*}/datasets/{dataset_id=*}/tables/{table_id=*}/rowAccessPolicies\x12\xee\x01\n" +
	"\x12GetRowAccessPolicy\x123.google.cloud.bigquery.v2.GetRowAccessPolicyRequest\x1a).google.cloud.bigquery.v2.RowAccessPolicy\"x\x82\xd3\xe4\x93\x02r\x12p/bigquery/v2/projects/{project_id=*}/datasets/{dataset_id=*}/tables/{table_id=*}/rowAccessPolicies/{policy_id=*}\x12\xf9\x01\n" +
	"\x15CreateRowAccessPolicy\x126.google.cloud.bigquery.v2.CreateRowAccessPolicyRequest\x1a).google.cloud.bigquery.v2.RowAccessPolicy\"}\x82\xd3\xe4\x93\x02w:\x11row_access_policy\"b/bigquery/v2/projects/{project_id=*}/datasets/{dataset_id=*}/tables/{table_id=*}/rowAccessPolicies\x12\x89\x02\n" +
	"\x15UpdateRowAccessPolicy\x126.google.cloud.bigquery.v2.UpdateRowAccessPolicyRequest\x1a).google.cloud.bigquery.v2.RowAccessPolicy\"\x8c\x01\x82\xd3\xe4\x93\x02\x85\x01:\x11row_access_policy\x1ap/bigquery/v2/projects/{project_id=*}/datasets/{dataset_id=*}/tables/{table_id=*}/rowAccessPolicies/{policy_id=*}\x12\xe1\x01\n" +
	"\x15DeleteRowAccessPolicy\x126.google.cloud.bigquery.v2.DeleteRowAccessPolicyRequest\x1a\x16.google.protobuf.Empty\"x\x82\xd3\xe4\x93\x02r*p/bigquery/v2/projects/{project_id=*}/datasets/{dataset_id=*}/tables/{table_id=*}/rowAccessPolicies/{policy_id=*}\x12\xf0\x01\n" +
	"\x1cBatchDeleteRowAccessPolicies\x12=.google.cloud.bigquery.v2.BatchDeleteRowAccessPoliciesRequest\x1a\x16.google.protobuf.Empty\"y\x82\xd3\xe4\x93\x02s:\x01*\"n/bigquery/v2/projects/{project_id=*}/datasets/{dataset_id=*}/tables/{table_id=*}/rowAccessPolicies:batchDelete\x1a\xae\x01\xcaA\x17bigquery.googleapis.com\xd2A\x90\x01https://www.googleapis.com/auth/bigquery,https://www.googleapis.com/auth/cloud-platform,https://www.googleapis.com/auth/cloud-platform.read-onlyBs\n" +
	"\x1ccom.google.cloud.bigquery.v2B\x14RowAccessPolicyProtoP\x01Z;cloud.google.com/go/bigquery/v2/apiv2/bigquerypb;bigquerypbb\x06proto3"

var file_google_cloud_bigquery_v2_row_access_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_google_cloud_bigquery_v2_row_access_policy_proto_goTypes = []any{
	(*ListRowAccessPoliciesRequest)(nil),        // 0: google.cloud.bigquery.v2.ListRowAccessPoliciesRequest
	(*ListRowAccessPoliciesResponse)(nil),       // 1: google.cloud.bigquery.v2.ListRowAccessPoliciesResponse
	(*GetRowAccessPolicyRequest)(nil),           // 2: google.cloud.bigquery.v2.GetRowAccessPolicyRequest
	(*CreateRowAccessPolicyRequest)(nil),        // 3: google.cloud.bigquery.v2.CreateRowAccessPolicyRequest
	(*UpdateRowAccessPolicyRequest)(nil),        // 4: google.cloud.bigquery.v2.UpdateRowAccessPolicyRequest
	(*DeleteRowAccessPolicyRequest)(nil),        // 5: google.cloud.bigquery.v2.DeleteRowAccessPolicyRequest
	(*BatchDeleteRowAccessPoliciesRequest)(nil), // 6: google.cloud.bigquery.v2.BatchDeleteRowAccessPoliciesRequest
	(*RowAccessPolicy)(nil),                     // 7: google.cloud.bigquery.v2.RowAccessPolicy
	(*RowAccessPolicyReference)(nil),            // 8: google.cloud.bigquery.v2.RowAccessPolicyReference
	(*timestamppb.Timestamp)(nil),               // 9: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                       // 10: google.protobuf.Empty
}
var file_google_cloud_bigquery_v2_row_access_policy_proto_depIdxs = []int32{
	7,  // 0: google.cloud.bigquery.v2.ListRowAccessPoliciesResponse.row_access_policies:type_name -> google.cloud.bigquery.v2.RowAccessPolicy
	7,  // 1: google.cloud.bigquery.v2.CreateRowAccessPolicyRequest.row_access_policy:type_name -> google.cloud.bigquery.v2.RowAccessPolicy
	7,  // 2: google.cloud.bigquery.v2.UpdateRowAccessPolicyRequest.row_access_policy:type_name -> google.cloud.bigquery.v2.RowAccessPolicy
	8,  // 3: google.cloud.bigquery.v2.RowAccessPolicy.row_access_policy_reference:type_name -> google.cloud.bigquery.v2.RowAccessPolicyReference
	9,  // 4: google.cloud.bigquery.v2.RowAccessPolicy.creation_time:type_name -> google.protobuf.Timestamp
	9,  // 5: google.cloud.bigquery.v2.RowAccessPolicy.last_modified_time:type_name -> google.protobuf.Timestamp
	0,  // 6: google.cloud.bigquery.v2.RowAccessPolicyService.ListRowAccessPolicies:input_type -> google.cloud.bigquery.v2.ListRowAccessPoliciesRequest
	2,  // 7: google.cloud.bigquery.v2.RowAccessPolicyService.GetRowAccessPolicy:input_type -> google.cloud.bigquery.v2.GetRowAccessPolicyRequest
	3,  // 8: google.cloud.bigquery.v2.RowAccessPolicyService.CreateRowAccessPolicy:input_type -> google.cloud.bigquery.v2.CreateRowAccessPolicyRequest
	4,  // 9: google.cloud.bigquery.v2.RowAccessPolicyService.UpdateRowAccessPolicy:input_type -> google.cloud.bigquery.v2.UpdateRowAccessPolicyRequest
	5,  // 10: google.cloud.bigquery.v2.RowAccessPolicyService.DeleteRowAccessPolicy:input_type -> google.cloud.bigquery.v2.DeleteRowAccessPolicyRequest
	6,  // 11: google.cloud.bigquery.v2.RowAccessPolicyService.BatchDeleteRowAccessPolicies:input_type -> google.cloud.bigquery.v2.BatchDeleteRowAccessPoliciesRequest
	1,  // 12: google.cloud.bigquery.v2.RowAccessPolicyService.ListRowAccessPolicies:output_type -> google.cloud.bigquery.v2.ListRowAccessPoliciesResponse
	7,  // 13: google.cloud.bigquery.v2.RowAccessPolicyService.GetRowAccessPolicy:output_type -> google.cloud.bigquery.v2.RowAccessPolicy
	7,  // 14: google.cloud.bigquery.v2.RowAccessPolicyService.CreateRowAccessPolicy:output_type -> google.cloud.bigquery.v2.RowAccessPolicy
	7,  // 15: google.cloud.bigquery.v2.RowAccessPolicyService.UpdateRowAccessPolicy:output_type -> google.cloud.bigquery.v2.RowAccessPolicy
	10, // 16: google.cloud.bigquery.v2.RowAccessPolicyService.DeleteRowAccessPolicy:output_type -> google.protobuf.Empty
	10, // 17: google.cloud.bigquery.v2.RowAccessPolicyService.BatchDeleteRowAccessPolicies:output_type -> google.protobuf.Empty
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_google_cloud_bigquery_v2_row_access_policy_proto_init() }
func file_google_cloud_bigquery_v2_row_access_policy_proto_init() {
	if File_google_cloud_bigquery_v2_row_access_policy_proto != nil {
		return
	}
	file_google_cloud_bigquery_v2_row_access_policy_reference_proto_init()
	file_google_cloud_bigquery_v2_row_access_policy_proto_msgTypes[5].OneofWrappers = []any{}
	file_google_cloud_bigquery_v2_row_access_policy_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_google_cloud_bigquery_v2_row_access_policy_proto_rawDesc), len(file_google_cloud_bigquery_v2_row_access_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_google_cloud_bigquery_v2_row_access_policy_proto_goTypes,
		DependencyIndexes: file_google_cloud_bigquery_v2_row_access_policy_proto_depIdxs,
		MessageInfos:      file_google_cloud_bigquery_v2_row_access_policy_proto_msgTypes,
	}.Build()
	File_google_cloud_bigquery_v2_row_access_policy_proto = out.File
	file_google_cloud_bigquery_v2_row_access_policy_proto_goTypes = nil
	file_google_cloud_bigquery_v2_row_access_policy_proto_depIdxs = nil
}
