// Code generated by protoc-gen-go. DO NOT EDIT.
// source: testmsg.proto

package storage

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TestMsg struct {
	Name                 *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Intval               *int64   `protobuf:"varint,2,opt,name=intval" json:"intval,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestMsg) Reset()         { *m = TestMsg{} }
func (m *TestMsg) String() string { return proto.CompactTextString(m) }
func (*TestMsg) ProtoMessage()    {}
func (*TestMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcadc46d8d7f388e, []int{0}
}

func (m *TestMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestMsg.Unmarshal(m, b)
}
func (m *TestMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestMsg.Marshal(b, m, deterministic)
}
func (m *TestMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestMsg.Merge(m, src)
}
func (m *TestMsg) XXX_Size() int {
	return xxx_messageInfo_TestMsg.Size(m)
}
func (m *TestMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_TestMsg.DiscardUnknown(m)
}

var xxx_messageInfo_TestMsg proto.InternalMessageInfo

func (m *TestMsg) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *TestMsg) GetIntval() int64 {
	if m != nil && m.Intval != nil {
		return *m.Intval
	}
	return 0
}

func init() {
	proto.RegisterType((*TestMsg)(nil), "storage.TestMsg")
}

func init() { proto.RegisterFile("testmsg.proto", fileDescriptor_fcadc46d8d7f388e) }

var fileDescriptor_fcadc46d8d7f388e = []byte{
	// 95 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x49, 0x2d, 0x2e,
	0xc9, 0x2d, 0x4e, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f, 0x2e, 0xc9, 0x2f, 0x4a,
	0x4c, 0x4f, 0x55, 0x32, 0xe5, 0x62, 0x0f, 0x49, 0x2d, 0x2e, 0xf1, 0x2d, 0x4e, 0x17, 0x12, 0xe2,
	0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x85, 0xc4,
	0xb8, 0xd8, 0x32, 0xf3, 0x4a, 0xca, 0x12, 0x73, 0x24, 0x98, 0x14, 0x18, 0x35, 0x98, 0x83, 0xa0,
	0x3c, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0f, 0x98, 0xcc, 0x92, 0x4f, 0x00, 0x00, 0x00,
}
